// Package agenthostcontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package agenthostcontract

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	LocalBearerScopes localBearerContextKey = "localBearer.Scopes"
)

// Defines values for AgentHostStatusRuntimeMode.
const (
	ManagedStdio AgentHostStatusRuntimeMode = "managed-stdio"
)

// Valid indicates whether the value is a known member of the AgentHostStatusRuntimeMode enum.
func (e AgentHostStatusRuntimeMode) Valid() bool {
	switch e {
	case ManagedStdio:
		return true
	default:
		return false
	}
}

// Defines values for AgentHostStatusService.
const (
	AgentHostStatusServiceYijieAgentHost AgentHostStatusService = "yijie-agent-host"
)

// Valid indicates whether the value is a known member of the AgentHostStatusService enum.
func (e AgentHostStatusService) Valid() bool {
	switch e {
	case AgentHostStatusServiceYijieAgentHost:
		return true
	default:
		return false
	}
}

// Defines values for AgentHostStatusStatus.
const (
	AgentHostStatusStatusDegraded AgentHostStatusStatus = "degraded"
	AgentHostStatusStatusOk       AgentHostStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the AgentHostStatusStatus enum.
func (e AgentHostStatusStatus) Valid() bool {
	switch e {
	case AgentHostStatusStatusDegraded:
		return true
	case AgentHostStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionFailureCode.
const (
	AgentSessionFailureCodeEmpty                       AgentSessionFailureCode = ""
	AgentSessionFailureCodeProviderIdentityMismatch    AgentSessionFailureCode = "provider_identity_mismatch"
	AgentSessionFailureCodeThreadResumeFailed          AgentSessionFailureCode = "thread_resume_failed"
	AgentSessionFailureCodeThreadResumeResponseInvalid AgentSessionFailureCode = "thread_resume_response_invalid"
	AgentSessionFailureCodeThreadStartFailed           AgentSessionFailureCode = "thread_start_failed"
	AgentSessionFailureCodeThreadStartResponseInvalid  AgentSessionFailureCode = "thread_start_response_invalid"
	AgentSessionFailureCodeTurnStartFailed             AgentSessionFailureCode = "turn_start_failed"
	AgentSessionFailureCodeTurnStartResponseInvalid    AgentSessionFailureCode = "turn_start_response_invalid"
)

// Valid indicates whether the value is a known member of the AgentSessionFailureCode enum.
func (e AgentSessionFailureCode) Valid() bool {
	switch e {
	case AgentSessionFailureCodeEmpty:
		return true
	case AgentSessionFailureCodeProviderIdentityMismatch:
		return true
	case AgentSessionFailureCodeThreadResumeFailed:
		return true
	case AgentSessionFailureCodeThreadResumeResponseInvalid:
		return true
	case AgentSessionFailureCodeThreadStartFailed:
		return true
	case AgentSessionFailureCodeThreadStartResponseInvalid:
		return true
	case AgentSessionFailureCodeTurnStartFailed:
		return true
	case AgentSessionFailureCodeTurnStartResponseInvalid:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionModel.
const (
	AgentSessionModelEmpty     AgentSessionModel = ""
	AgentSessionModelMiniMaxM3 AgentSessionModel = "MiniMax-M3"
)

// Valid indicates whether the value is a known member of the AgentSessionModel enum.
func (e AgentSessionModel) Valid() bool {
	switch e {
	case AgentSessionModelEmpty:
		return true
	case AgentSessionModelMiniMaxM3:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionModelProvider.
const (
	AgentSessionModelProviderEmpty   AgentSessionModelProvider = ""
	AgentSessionModelProviderMinimax AgentSessionModelProvider = "minimax"
)

// Valid indicates whether the value is a known member of the AgentSessionModelProvider enum.
func (e AgentSessionModelProvider) Valid() bool {
	switch e {
	case AgentSessionModelProviderEmpty:
		return true
	case AgentSessionModelProviderMinimax:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionState.
const (
	AgentSessionStateActive   AgentSessionState = "active"
	AgentSessionStateFailed   AgentSessionState = "failed"
	AgentSessionStateIdle     AgentSessionState = "idle"
	AgentSessionStateStarting AgentSessionState = "starting"
)

// Valid indicates whether the value is a known member of the AgentSessionState enum.
func (e AgentSessionState) Valid() bool {
	switch e {
	case AgentSessionStateActive:
		return true
	case AgentSessionStateFailed:
		return true
	case AgentSessionStateIdle:
		return true
	case AgentSessionStateStarting:
		return true
	default:
		return false
	}
}

// Defines values for CleanupAgentSessionV2CompletedResponseOutcome.
const (
	CleanupAgentSessionV2CompletedResponseOutcomeComplete CleanupAgentSessionV2CompletedResponseOutcome = "complete"
)

// Valid indicates whether the value is a known member of the CleanupAgentSessionV2CompletedResponseOutcome enum.
func (e CleanupAgentSessionV2CompletedResponseOutcome) Valid() bool {
	switch e {
	case CleanupAgentSessionV2CompletedResponseOutcomeComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupAgentSessionV2IncompleteResponseOutcome.
const (
	CleanupAgentSessionV2IncompleteResponseOutcomeIncomplete CleanupAgentSessionV2IncompleteResponseOutcome = "incomplete"
)

// Valid indicates whether the value is a known member of the CleanupAgentSessionV2IncompleteResponseOutcome enum.
func (e CleanupAgentSessionV2IncompleteResponseOutcome) Valid() bool {
	switch e {
	case CleanupAgentSessionV2IncompleteResponseOutcomeIncomplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupCompletedSurfacesHostMapping.
const (
	CleanupCompletedSurfacesHostMappingComplete CleanupCompletedSurfacesHostMapping = "complete"
)

// Valid indicates whether the value is a known member of the CleanupCompletedSurfacesHostMapping enum.
func (e CleanupCompletedSurfacesHostMapping) Valid() bool {
	switch e {
	case CleanupCompletedSurfacesHostMappingComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupCompletedSurfacesHostReplay.
const (
	CleanupCompletedSurfacesHostReplayComplete CleanupCompletedSurfacesHostReplay = "complete"
)

// Valid indicates whether the value is a known member of the CleanupCompletedSurfacesHostReplay enum.
func (e CleanupCompletedSurfacesHostReplay) Valid() bool {
	switch e {
	case CleanupCompletedSurfacesHostReplayComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupCompletedSurfacesRuntimeThreadTree.
const (
	CleanupCompletedSurfacesRuntimeThreadTreeComplete CleanupCompletedSurfacesRuntimeThreadTree = "complete"
)

// Valid indicates whether the value is a known member of the CleanupCompletedSurfacesRuntimeThreadTree enum.
func (e CleanupCompletedSurfacesRuntimeThreadTree) Valid() bool {
	switch e {
	case CleanupCompletedSurfacesRuntimeThreadTreeComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupIncompleteErrorCode.
const (
	CleanupIncomplete CleanupIncompleteErrorCode = "cleanup_incomplete"
)

// Valid indicates whether the value is a known member of the CleanupIncompleteErrorCode enum.
func (e CleanupIncompleteErrorCode) Valid() bool {
	switch e {
	case CleanupIncomplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupIncompleteErrorReasonCode.
const (
	CleanupIncompleteErrorReasonCodeActiveTurn                CleanupIncompleteErrorReasonCode = "active_turn"
	CleanupIncompleteErrorReasonCodeHostMappingCleanupFailed  CleanupIncompleteErrorReasonCode = "host_mapping_cleanup_failed"
	CleanupIncompleteErrorReasonCodeHostReplayCleanupFailed   CleanupIncompleteErrorReasonCode = "host_replay_cleanup_failed"
	CleanupIncompleteErrorReasonCodeInternalError             CleanupIncompleteErrorReasonCode = "internal_error"
	CleanupIncompleteErrorReasonCodeOperationStateUnavailable CleanupIncompleteErrorReasonCode = "operation_state_unavailable"
	CleanupIncompleteErrorReasonCodeRuntimeDeleteFailed       CleanupIncompleteErrorReasonCode = "runtime_delete_failed"
	CleanupIncompleteErrorReasonCodeRuntimeDeleteUnconfirmed  CleanupIncompleteErrorReasonCode = "runtime_delete_unconfirmed"
	CleanupIncompleteErrorReasonCodeSharedThreadMapping       CleanupIncompleteErrorReasonCode = "shared_thread_mapping"
	CleanupIncompleteErrorReasonCodeTerminalUnconfirmed       CleanupIncompleteErrorReasonCode = "terminal_unconfirmed"
)

// Valid indicates whether the value is a known member of the CleanupIncompleteErrorReasonCode enum.
func (e CleanupIncompleteErrorReasonCode) Valid() bool {
	switch e {
	case CleanupIncompleteErrorReasonCodeActiveTurn:
		return true
	case CleanupIncompleteErrorReasonCodeHostMappingCleanupFailed:
		return true
	case CleanupIncompleteErrorReasonCodeHostReplayCleanupFailed:
		return true
	case CleanupIncompleteErrorReasonCodeInternalError:
		return true
	case CleanupIncompleteErrorReasonCodeOperationStateUnavailable:
		return true
	case CleanupIncompleteErrorReasonCodeRuntimeDeleteFailed:
		return true
	case CleanupIncompleteErrorReasonCodeRuntimeDeleteUnconfirmed:
		return true
	case CleanupIncompleteErrorReasonCodeSharedThreadMapping:
		return true
	case CleanupIncompleteErrorReasonCodeTerminalUnconfirmed:
		return true
	default:
		return false
	}
}

// Defines values for CleanupOperationConflictErrorErrorCode.
const (
	CleanupOperationConflict CleanupOperationConflictErrorErrorCode = "cleanup_operation_conflict"
)

// Valid indicates whether the value is a known member of the CleanupOperationConflictErrorErrorCode enum.
func (e CleanupOperationConflictErrorErrorCode) Valid() bool {
	switch e {
	case CleanupOperationConflict:
		return true
	default:
		return false
	}
}

// Defines values for CleanupSurfaceStatus.
const (
	CleanupSurfaceStatusComplete     CleanupSurfaceStatus = "complete"
	CleanupSurfaceStatusIncomplete   CleanupSurfaceStatus = "incomplete"
	CleanupSurfaceStatusNotAttempted CleanupSurfaceStatus = "not_attempted"
)

// Valid indicates whether the value is a known member of the CleanupSurfaceStatus enum.
func (e CleanupSurfaceStatus) Valid() bool {
	switch e {
	case CleanupSurfaceStatusComplete:
		return true
	case CleanupSurfaceStatusIncomplete:
		return true
	case CleanupSurfaceStatusNotAttempted:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ErrorResponseErrorCodeEventReplayUnavailable ErrorResponseErrorCode = "event_replay_unavailable"
	ErrorResponseErrorCodeEventStreamChanged     ErrorResponseErrorCode = "event_stream_changed"
	ErrorResponseErrorCodeInternalError          ErrorResponseErrorCode = "internal_error"
	ErrorResponseErrorCodeInvalidEventCursor     ErrorResponseErrorCode = "invalid_event_cursor"
	ErrorResponseErrorCodeInvalidRequest         ErrorResponseErrorCode = "invalid_request"
	ErrorResponseErrorCodeRuntimeRequestFailed   ErrorResponseErrorCode = "runtime_request_failed"
	ErrorResponseErrorCodeSessionNotFound        ErrorResponseErrorCode = "session_not_found"
	ErrorResponseErrorCodeSessionNotUsable       ErrorResponseErrorCode = "session_not_usable"
	ErrorResponseErrorCodeStreamingUnsupported   ErrorResponseErrorCode = "streaming_unsupported"
	ErrorResponseErrorCodeTaskSessionExists      ErrorResponseErrorCode = "task_session_exists"
	ErrorResponseErrorCodeTurnActive             ErrorResponseErrorCode = "turn_active"
	ErrorResponseErrorCodeTurnNotActive          ErrorResponseErrorCode = "turn_not_active"
	ErrorResponseErrorCodeUnauthorized           ErrorResponseErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ErrorResponseErrorCodeEventReplayUnavailable:
		return true
	case ErrorResponseErrorCodeEventStreamChanged:
		return true
	case ErrorResponseErrorCodeInternalError:
		return true
	case ErrorResponseErrorCodeInvalidEventCursor:
		return true
	case ErrorResponseErrorCodeInvalidRequest:
		return true
	case ErrorResponseErrorCodeRuntimeRequestFailed:
		return true
	case ErrorResponseErrorCodeSessionNotFound:
		return true
	case ErrorResponseErrorCodeSessionNotUsable:
		return true
	case ErrorResponseErrorCodeStreamingUnsupported:
		return true
	case ErrorResponseErrorCodeTaskSessionExists:
		return true
	case ErrorResponseErrorCodeTurnActive:
		return true
	case ErrorResponseErrorCodeTurnNotActive:
		return true
	case ErrorResponseErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseService.
const (
	HealthResponseServiceYijieAgentHost HealthResponseService = "yijie-agent-host"
)

// Valid indicates whether the value is a known member of the HealthResponseService enum.
func (e HealthResponseService) Valid() bool {
	switch e {
	case HealthResponseServiceYijieAgentHost:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for NotReadyResponseStatus.
const (
	NotReady NotReadyResponseStatus = "not_ready"
)

// Valid indicates whether the value is a known member of the NotReadyResponseStatus enum.
func (e NotReadyResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseRuntimeState.
const (
	ReadyResponseRuntimeStateReady ReadyResponseRuntimeState = "ready"
)

// Valid indicates whether the value is a known member of the ReadyResponseRuntimeState enum.
func (e ReadyResponseRuntimeState) Valid() bool {
	switch e {
	case ReadyResponseRuntimeStateReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseStatus.
const (
	ReadyResponseStatusReady ReadyResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyResponseStatus enum.
func (e ReadyResponseStatus) Valid() bool {
	switch e {
	case ReadyResponseStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeState.
const (
	RuntimeStateFailed        RuntimeState = "failed"
	RuntimeStateInitializing  RuntimeState = "initializing"
	RuntimeStateNotConfigured RuntimeState = "not_configured"
	RuntimeStateReady         RuntimeState = "ready"
	RuntimeStateStarting      RuntimeState = "starting"
	RuntimeStateStopped       RuntimeState = "stopped"
	RuntimeStateStopping      RuntimeState = "stopping"
	RuntimeStateVerifying     RuntimeState = "verifying"
)

// Valid indicates whether the value is a known member of the RuntimeState enum.
func (e RuntimeState) Valid() bool {
	switch e {
	case RuntimeStateFailed:
		return true
	case RuntimeStateInitializing:
		return true
	case RuntimeStateNotConfigured:
		return true
	case RuntimeStateReady:
		return true
	case RuntimeStateStarting:
		return true
	case RuntimeStateStopped:
		return true
	case RuntimeStateStopping:
		return true
	case RuntimeStateVerifying:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusExperimentalApi.
const (
	False RuntimeStatusExperimentalApi = false
)

// Valid indicates whether the value is a known member of the RuntimeStatusExperimentalApi enum.
func (e RuntimeStatusExperimentalApi) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusFailureCode.
const (
	ArtifactVerificationFailed    RuntimeStatusFailureCode = "artifact_verification_failed"
	InitializeFailed              RuntimeStatusFailureCode = "initialize_failed"
	InitializeResponseInvalid     RuntimeStatusFailureCode = "initialize_response_invalid"
	InitializedNotificationFailed RuntimeStatusFailureCode = "initialized_notification_failed"
	ProtocolFailure               RuntimeStatusFailureCode = "protocol_failure"
	ProviderConfigFailed          RuntimeStatusFailureCode = "provider_config_failed"
	RuntimeConfigInvalid          RuntimeStatusFailureCode = "runtime_config_invalid"
	RuntimeDisconnected           RuntimeStatusFailureCode = "runtime_disconnected"
	RuntimeExited                 RuntimeStatusFailureCode = "runtime_exited"
	RuntimeNotConfigured          RuntimeStatusFailureCode = "runtime_not_configured"
	RuntimeStartFailed            RuntimeStatusFailureCode = "runtime_start_failed"
	StartupCancelled              RuntimeStatusFailureCode = "startup_cancelled"
)

// Valid indicates whether the value is a known member of the RuntimeStatusFailureCode enum.
func (e RuntimeStatusFailureCode) Valid() bool {
	switch e {
	case ArtifactVerificationFailed:
		return true
	case InitializeFailed:
		return true
	case InitializeResponseInvalid:
		return true
	case InitializedNotificationFailed:
		return true
	case ProtocolFailure:
		return true
	case ProviderConfigFailed:
		return true
	case RuntimeConfigInvalid:
		return true
	case RuntimeDisconnected:
		return true
	case RuntimeExited:
		return true
	case RuntimeNotConfigured:
		return true
	case RuntimeStartFailed:
		return true
	case StartupCancelled:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusModel.
const (
	MiniMaxM3 RuntimeStatusModel = "MiniMax-M3"
)

// Valid indicates whether the value is a known member of the RuntimeStatusModel enum.
func (e RuntimeStatusModel) Valid() bool {
	switch e {
	case MiniMaxM3:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusModelProvider.
const (
	RuntimeStatusModelProviderMinimax RuntimeStatusModelProvider = "minimax"
)

// Valid indicates whether the value is a known member of the RuntimeStatusModelProvider enum.
func (e RuntimeStatusModelProvider) Valid() bool {
	switch e {
	case RuntimeStatusModelProviderMinimax:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusRuntimeVersion.
const (
	N01446 RuntimeStatusRuntimeVersion = "0.144.6"
)

// Valid indicates whether the value is a known member of the RuntimeStatusRuntimeVersion enum.
func (e RuntimeStatusRuntimeVersion) Valid() bool {
	switch e {
	case N01446:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusTransport.
const (
	Stdio RuntimeStatusTransport = "stdio"
)

// Valid indicates whether the value is a known member of the RuntimeStatusTransport enum.
func (e RuntimeStatusTransport) Valid() bool {
	switch e {
	case Stdio:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusUpstreamCommit.
const (
	N5d1fbf26c43abc65a203928b2e31561cb039e06d RuntimeStatusUpstreamCommit = "5d1fbf26c43abc65a203928b2e31561cb039e06d"
)

// Valid indicates whether the value is a known member of the RuntimeStatusUpstreamCommit enum.
func (e RuntimeStatusUpstreamCommit) Valid() bool {
	switch e {
	case N5d1fbf26c43abc65a203928b2e31561cb039e06d:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusUpstreamTag.
const (
	RustV01446 RuntimeStatusUpstreamTag = "rust-v0.144.6"
)

// Valid indicates whether the value is a known member of the RuntimeStatusUpstreamTag enum.
func (e RuntimeStatusUpstreamTag) Valid() bool {
	switch e {
	case RustV01446:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnRequestReasoningEffort.
const (
	Empty StartTurnRequestReasoningEffort = ""
	High  StartTurnRequestReasoningEffort = "high"
	None  StartTurnRequestReasoningEffort = "none"
)

// Valid indicates whether the value is a known member of the StartTurnRequestReasoningEffort enum.
func (e StartTurnRequestReasoningEffort) Valid() bool {
	switch e {
	case Empty:
		return true
	case High:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for TitleGenerationUnavailableErrorErrorCode.
const (
	TitleGenerationUnavailableErrorErrorCodeTitleGenerationUnavailable TitleGenerationUnavailableErrorErrorCode = "title_generation_unavailable"
)

// Valid indicates whether the value is a known member of the TitleGenerationUnavailableErrorErrorCode enum.
func (e TitleGenerationUnavailableErrorErrorCode) Valid() bool {
	switch e {
	case TitleGenerationUnavailableErrorErrorCodeTitleGenerationUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for TitleOperationConflictErrorErrorCode.
const (
	TitleOperationConflictErrorErrorCodeTitleOperationConflict TitleOperationConflictErrorErrorCode = "title_operation_conflict"
)

// Valid indicates whether the value is a known member of the TitleOperationConflictErrorErrorCode enum.
func (e TitleOperationConflictErrorErrorCode) Valid() bool {
	switch e {
	case TitleOperationConflictErrorErrorCodeTitleOperationConflict:
		return true
	default:
		return false
	}
}

// Defines values for TitleOutputInvalidErrorErrorCode.
const (
	TitleOutputInvalidErrorErrorCodeTitleOutputInvalid TitleOutputInvalidErrorErrorCode = "title_output_invalid"
)

// Valid indicates whether the value is a known member of the TitleOutputInvalidErrorErrorCode enum.
func (e TitleOutputInvalidErrorErrorCode) Valid() bool {
	switch e {
	case TitleOutputInvalidErrorErrorCodeTitleOutputInvalid:
		return true
	default:
		return false
	}
}

// Defines values for EventSchemaVersionV2.
const (
	EventSchemaVersionV2N2 EventSchemaVersionV2 = 2
)

// Valid indicates whether the value is a known member of the EventSchemaVersionV2 enum.
func (e EventSchemaVersionV2) Valid() bool {
	switch e {
	case EventSchemaVersionV2N2:
		return true
	default:
		return false
	}
}

// Defines values for StreamAgentSessionEventsV2ParamsEventSchemaVersion.
const (
	StreamAgentSessionEventsV2ParamsEventSchemaVersionN2 StreamAgentSessionEventsV2ParamsEventSchemaVersion = 2
)

// Valid indicates whether the value is a known member of the StreamAgentSessionEventsV2ParamsEventSchemaVersion enum.
func (e StreamAgentSessionEventsV2ParamsEventSchemaVersion) Valid() bool {
	switch e {
	case StreamAgentSessionEventsV2ParamsEventSchemaVersionN2:
		return true
	default:
		return false
	}
}

// AgentHostStatus defines model for AgentHostStatus.
type AgentHostStatus struct {
	Environment string                     `json:"environment"`
	Runtime     RuntimeStatus              `json:"runtime"`
	RuntimeMode AgentHostStatusRuntimeMode `json:"runtime_mode"`
	Service     AgentHostStatusService     `json:"service"`
	Status      AgentHostStatusStatus      `json:"status"`
}

// AgentHostStatusRuntimeMode defines model for AgentHostStatus.RuntimeMode.
type AgentHostStatusRuntimeMode string

// AgentHostStatusService defines model for AgentHostStatus.Service.
type AgentHostStatusService string

// AgentHostStatusStatus defines model for AgentHostStatus.Status.
type AgentHostStatusStatus string

// AgentSession defines model for AgentSession.
type AgentSession struct {
	// ActiveTurnId A UUID when bound, otherwise the empty string.
	ActiveTurnId   UuidOrEmpty        `json:"active_turn_id"`
	AgentSessionId openapi_types.UUID `json:"agent_session_id"`

	// CodexThreadId A UUID when bound, otherwise the empty string.
	CodexThreadId UuidOrEmpty `json:"codex_thread_id"`
	CreatedAt     time.Time   `json:"created_at"`

	// Cwd Rehydrated canonical absolute session working directory.
	Cwd           string                    `json:"cwd"`
	FailureCode   AgentSessionFailureCode   `json:"failure_code"`
	Model         AgentSessionModel         `json:"model"`
	ModelProvider AgentSessionModelProvider `json:"model_provider"`
	State         AgentSessionState         `json:"state"`
	TaskId        openapi_types.UUID        `json:"task_id"`
	UpdatedAt     time.Time                 `json:"updated_at"`
}

// AgentSessionFailureCode defines model for AgentSession.FailureCode.
type AgentSessionFailureCode string

// AgentSessionModel defines model for AgentSession.Model.
type AgentSessionModel string

// AgentSessionModelProvider defines model for AgentSession.ModelProvider.
type AgentSessionModelProvider string

// AgentSessionState defines model for AgentSession.State.
type AgentSessionState string

// CleanupAgentSessionV2CompletedResponse defines model for CleanupAgentSessionV2CompletedResponse.
type CleanupAgentSessionV2CompletedResponse struct {
	OperationId openapi_types.UUID                            `json:"operation_id"`
	Outcome     CleanupAgentSessionV2CompletedResponseOutcome `json:"outcome"`
	Surfaces    CleanupCompletedSurfaces                      `json:"surfaces"`
}

// CleanupAgentSessionV2CompletedResponseOutcome defines model for CleanupAgentSessionV2CompletedResponse.Outcome.
type CleanupAgentSessionV2CompletedResponseOutcome string

// CleanupAgentSessionV2IncompleteResponse defines model for CleanupAgentSessionV2IncompleteResponse.
type CleanupAgentSessionV2IncompleteResponse struct {
	Error       CleanupIncompleteError                         `json:"error"`
	OperationId openapi_types.UUID                             `json:"operation_id"`
	Outcome     CleanupAgentSessionV2IncompleteResponseOutcome `json:"outcome"`
	Surfaces    CleanupIncompleteSurfaces                      `json:"surfaces"`
}

// CleanupAgentSessionV2IncompleteResponseOutcome defines model for CleanupAgentSessionV2IncompleteResponse.Outcome.
type CleanupAgentSessionV2IncompleteResponseOutcome string

// CleanupAgentSessionV2Request defines model for CleanupAgentSessionV2Request.
type CleanupAgentSessionV2Request struct {
	// OperationId Idempotent deletion-saga operation identifier selected by Desktop.
	OperationId openapi_types.UUID `json:"operation_id"`

	// RequestId Correlation only; never authorization input.
	RequestId *string `json:"request_id,omitempty"`

	// TraceId Correlation only; never authorization input.
	TraceId *string `json:"trace_id,omitempty"`
}

// CleanupCompletedSurfaces defines model for CleanupCompletedSurfaces.
type CleanupCompletedSurfaces struct {
	HostMapping       CleanupCompletedSurfacesHostMapping       `json:"host_mapping"`
	HostReplay        CleanupCompletedSurfacesHostReplay        `json:"host_replay"`
	RuntimeThreadTree CleanupCompletedSurfacesRuntimeThreadTree `json:"runtime_thread_tree"`
}

// CleanupCompletedSurfacesHostMapping defines model for CleanupCompletedSurfaces.HostMapping.
type CleanupCompletedSurfacesHostMapping string

// CleanupCompletedSurfacesHostReplay defines model for CleanupCompletedSurfaces.HostReplay.
type CleanupCompletedSurfacesHostReplay string

// CleanupCompletedSurfacesRuntimeThreadTree defines model for CleanupCompletedSurfaces.RuntimeThreadTree.
type CleanupCompletedSurfacesRuntimeThreadTree string

// CleanupIncompleteError defines model for CleanupIncompleteError.
type CleanupIncompleteError struct {
	Code       CleanupIncompleteErrorCode       `json:"code"`
	Message    string                           `json:"message"`
	ReasonCode CleanupIncompleteErrorReasonCode `json:"reason_code"`
}

// CleanupIncompleteErrorCode defines model for CleanupIncompleteError.Code.
type CleanupIncompleteErrorCode string

// CleanupIncompleteErrorReasonCode defines model for CleanupIncompleteError.ReasonCode.
type CleanupIncompleteErrorReasonCode string

// CleanupIncompleteSurfaces defines model for CleanupIncompleteSurfaces.
type CleanupIncompleteSurfaces struct {
	HostMapping       CleanupSurfaceStatus `json:"host_mapping"`
	HostReplay        CleanupSurfaceStatus `json:"host_replay"`
	RuntimeThreadTree CleanupSurfaceStatus `json:"runtime_thread_tree"`
}

// CleanupOperationConflictError defines model for CleanupOperationConflictError.
type CleanupOperationConflictError struct {
	Error struct {
		Code    CleanupOperationConflictErrorErrorCode `json:"code"`
		Message string                                 `json:"message"`
	} `json:"error"`
}

// CleanupOperationConflictErrorErrorCode defines model for CleanupOperationConflictError.Error.Code.
type CleanupOperationConflictErrorErrorCode string

// CleanupSurfaceStatus defines model for CleanupSurfaceStatus.
type CleanupSurfaceStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// GenerateTitleV2Request defines model for GenerateTitleV2Request.
type GenerateTitleV2Request struct {
	// Input First user text only; non-blank and at most 8 KiB UTF-8.
	Input string `json:"input"`

	// OperationId Idempotent title-generation operation identifier selected by Desktop.
	OperationId openapi_types.UUID `json:"operation_id"`

	// RequestId Correlation only; never authorization input.
	RequestId *string `json:"request_id,omitempty"`

	// TraceId Correlation only; never authorization input.
	TraceId *string `json:"trace_id,omitempty"`
}

// GenerateTitleV2Response defines model for GenerateTitleV2Response.
type GenerateTitleV2Response struct {
	OperationId openapi_types.UUID `json:"operation_id"`

	// Title NFC, one-line untrusted plain text with 1..40 grapheme clusters and no control, bidi-control, HTML, or Markdown syntax.
	Title string `json:"title"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service HealthResponseService `json:"service"`
	Status  HealthResponseStatus  `json:"status"`
}

// HealthResponseService defines model for HealthResponse.Service.
type HealthResponseService string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// NotReadyResponse defines model for NotReadyResponse.
type NotReadyResponse struct {
	RuntimeState RuntimeState           `json:"runtime_state"`
	Status       NotReadyResponseStatus `json:"status"`
}

// NotReadyResponseStatus defines model for NotReadyResponse.Status.
type NotReadyResponseStatus string

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	RuntimeState ReadyResponseRuntimeState `json:"runtime_state"`
	Status       ReadyResponseStatus       `json:"status"`
}

// ReadyResponseRuntimeState defines model for ReadyResponse.RuntimeState.
type ReadyResponseRuntimeState string

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// RuntimeState defines model for RuntimeState.
type RuntimeState string

// RuntimeStatus defines model for RuntimeStatus.
type RuntimeStatus struct {
	ExperimentalApi RuntimeStatusExperimentalApi `json:"experimental_api"`
	FailureCode     *RuntimeStatusFailureCode    `json:"failure_code,omitempty"`
	Model           *RuntimeStatusModel          `json:"model,omitempty"`
	ModelProvider   *RuntimeStatusModelProvider  `json:"model_provider,omitempty"`
	Ready           bool                         `json:"ready"`
	RuntimeVersion  *RuntimeStatusRuntimeVersion `json:"runtime_version,omitempty"`
	State           RuntimeState                 `json:"state"`
	Transport       RuntimeStatusTransport       `json:"transport"`
	UpstreamCommit  *RuntimeStatusUpstreamCommit `json:"upstream_commit,omitempty"`
	UpstreamTag     *RuntimeStatusUpstreamTag    `json:"upstream_tag,omitempty"`
}

// RuntimeStatusExperimentalApi defines model for RuntimeStatus.ExperimentalApi.
type RuntimeStatusExperimentalApi bool

// RuntimeStatusFailureCode defines model for RuntimeStatus.FailureCode.
type RuntimeStatusFailureCode string

// RuntimeStatusModel defines model for RuntimeStatus.Model.
type RuntimeStatusModel string

// RuntimeStatusModelProvider defines model for RuntimeStatus.ModelProvider.
type RuntimeStatusModelProvider string

// RuntimeStatusRuntimeVersion defines model for RuntimeStatus.RuntimeVersion.
type RuntimeStatusRuntimeVersion string

// RuntimeStatusTransport defines model for RuntimeStatus.Transport.
type RuntimeStatusTransport string

// RuntimeStatusUpstreamCommit defines model for RuntimeStatus.UpstreamCommit.
type RuntimeStatusUpstreamCommit string

// RuntimeStatusUpstreamTag defines model for RuntimeStatus.UpstreamTag.
type RuntimeStatusUpstreamTag string

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	Session AgentSession `json:"session"`
}

// StartSessionRequest defines model for StartSessionRequest.
type StartSessionRequest struct {
	// Cwd Existing absolute local directory. Host resolves symlinks and uses the
	// resulting canonical path as the session working directory. Any private
	// persistence representation is an implementation detail and is not part
	// of this wire contract.
	Cwd string `json:"cwd"`

	// RequestId Optional request correlation identifier copied to session events.
	RequestId *string `json:"request_id,omitempty"`

	// TenantId Optional correlation context only; it does not grant tenant access.
	TenantId *string `json:"tenant_id,omitempty"`

	// TraceId Optional correlation identifier copied to session events.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId Optional correlation context only; it does not authenticate a user.
	UserId *string `json:"user_id,omitempty"`
}

// StartTurnRequest defines model for StartTurnRequest.
type StartTurnRequest struct {
	// Input Text-only turn input. It must contain a non-whitespace character and
	// must not exceed 1 MiB in UTF-8 bytes. The complete JSON body is also
	// capped at 1 MiB.
	Input string `json:"input"`

	// ReasoningEffort Omit or send the empty string for `none`; clients should prefer omission, `none`, or `high`.
	ReasoningEffort *StartTurnRequestReasoningEffort `json:"reasoning_effort,omitempty"`

	// RequestId Optional request correlation identifier copied to events from this operation onward.
	RequestId *string `json:"request_id,omitempty"`

	// TenantId Optional correlation context only; it does not grant tenant access.
	TenantId *string `json:"tenant_id,omitempty"`

	// TraceId Optional correlation identifier copied to events from this operation onward.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId Optional correlation context only; it does not authenticate a user.
	UserId *string `json:"user_id,omitempty"`
}

// StartTurnRequestReasoningEffort Omit or send the empty string for `none`; clients should prefer omission, `none`, or `high`.
type StartTurnRequestReasoningEffort string

// StartTurnResponse defines model for StartTurnResponse.
type StartTurnResponse struct {
	TurnId openapi_types.UUID `json:"turn_id"`
}

// TitleGenerationUnavailableError defines model for TitleGenerationUnavailableError.
type TitleGenerationUnavailableError struct {
	Error struct {
		Code    TitleGenerationUnavailableErrorErrorCode `json:"code"`
		Message string                                   `json:"message"`
	} `json:"error"`
}

// TitleGenerationUnavailableErrorErrorCode defines model for TitleGenerationUnavailableError.Error.Code.
type TitleGenerationUnavailableErrorErrorCode string

// TitleOperationConflictError defines model for TitleOperationConflictError.
type TitleOperationConflictError struct {
	Error struct {
		Code    TitleOperationConflictErrorErrorCode `json:"code"`
		Message string                               `json:"message"`
	} `json:"error"`
}

// TitleOperationConflictErrorErrorCode defines model for TitleOperationConflictError.Error.Code.
type TitleOperationConflictErrorErrorCode string

// TitleOutputInvalidError defines model for TitleOutputInvalidError.
type TitleOutputInvalidError struct {
	Error struct {
		Code    TitleOutputInvalidErrorErrorCode `json:"code"`
		Message string                           `json:"message"`
	} `json:"error"`
}

// TitleOutputInvalidErrorErrorCode defines model for TitleOutputInvalidError.Error.Code.
type TitleOutputInvalidErrorErrorCode string

// TraceRequest Correlation metadata copied to subsequent events. `{}` is valid. These
// values are correlation context, not authentication or authorization input.
type TraceRequest struct {
	RequestId *string `json:"request_id,omitempty"`
	TenantId  *string `json:"tenant_id,omitempty"`
	TraceId   *string `json:"trace_id,omitempty"`
	UserId    *string `json:"user_id,omitempty"`
}

// UuidOrEmpty A UUID when bound, otherwise the empty string.
type UuidOrEmpty = string

// AgentSessionId defines model for AgentSessionId.
type AgentSessionId = openapi_types.UUID

// EventAfter defines model for EventAfter.
type EventAfter = uint64

// EventSchemaVersionV2 defines model for EventSchemaVersionV2.
type EventSchemaVersionV2 int32

// EventStreamId defines model for EventStreamId.
type EventStreamId = openapi_types.UUID

// LastEventId defines model for LastEventId.
type LastEventId = string

// TaskId defines model for TaskId.
type TaskId = openapi_types.UUID

// TurnId defines model for TurnId.
type TurnId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// RuntimeRequestFailed defines model for RuntimeRequestFailed.
type RuntimeRequestFailed = ErrorResponse

// SessionNotFound defines model for SessionNotFound.
type SessionNotFound = ErrorResponse

// TitleGenerationUnavailable defines model for TitleGenerationUnavailable.
type TitleGenerationUnavailable = TitleGenerationUnavailableError

// TitleOperationConflict defines model for TitleOperationConflict.
type TitleOperationConflict = TitleOperationConflictError

// TitleOutputInvalid defines model for TitleOutputInvalid.
type TitleOutputInvalid = TitleOutputInvalidError

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// localBearerContextKey is the context key for localBearer security scheme
type localBearerContextKey string

// StreamAgentSessionEventsParams defines parameters for StreamAgentSessionEvents.
type StreamAgentSessionEventsParams struct {
	// StreamId Expected process-local stream identifier. Required when `after > 0`
	// unless `Last-Event-ID` supplies the complete cursor. A mismatch returns
	// `409 event_stream_changed`.
	StreamId *EventStreamId `form:"stream_id,omitempty" json:"stream_id,omitempty"`

	// After Unsigned 64-bit sequence after which events are replayed. Defaults to
	// zero. Values greater than zero require a matching stream ID. Ignored when
	// `Last-Event-ID` is present.
	After *EventAfter `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID Complete SSE cursor `<stream_id>:<sequence>`. Sequence is a decimal
	// unsigned 64-bit integer from 1 through 18446744073709551615 with no
	// leading zero. The header overrides `stream_id` and `after` query parameters.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// CleanupAgentSessionV2409JSONResponseBody defines parameters for CleanupAgentSessionV2.
type CleanupAgentSessionV2409JSONResponseBody struct {
	union json.RawMessage
}

// StreamAgentSessionEventsV2Params defines parameters for StreamAgentSessionEventsV2.
type StreamAgentSessionEventsV2Params struct {
	// EventSchemaVersion Explicit negotiation guard. Only integer value 2 is accepted on the v2 event stream.
	EventSchemaVersion StreamAgentSessionEventsV2ParamsEventSchemaVersion `form:"event_schema_version" json:"event_schema_version"`

	// StreamId Expected process-local stream identifier. Required when `after > 0`
	// unless `Last-Event-ID` supplies the complete cursor. A mismatch returns
	// `409 event_stream_changed`.
	StreamId *EventStreamId `form:"stream_id,omitempty" json:"stream_id,omitempty"`

	// After Unsigned 64-bit sequence after which events are replayed. Defaults to
	// zero. Values greater than zero require a matching stream ID. Ignored when
	// `Last-Event-ID` is present.
	After *EventAfter `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID Complete SSE cursor `<stream_id>:<sequence>`. Sequence is a decimal
	// unsigned 64-bit integer from 1 through 18446744073709551615 with no
	// leading zero. The header overrides `stream_id` and `after` query parameters.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// StreamAgentSessionEventsV2ParamsEventSchemaVersion defines parameters for StreamAgentSessionEventsV2.
type StreamAgentSessionEventsV2ParamsEventSchemaVersion int32

// ResumeAgentSessionJSONRequestBody defines body for ResumeAgentSession for application/json ContentType.
type ResumeAgentSessionJSONRequestBody = TraceRequest

// StartAgentTurnJSONRequestBody defines body for StartAgentTurn for application/json ContentType.
type StartAgentTurnJSONRequestBody = StartTurnRequest

// InterruptAgentTurnJSONRequestBody defines body for InterruptAgentTurn for application/json ContentType.
type InterruptAgentTurnJSONRequestBody = TraceRequest

// StartAgentSessionJSONRequestBody defines body for StartAgentSession for application/json ContentType.
type StartAgentSessionJSONRequestBody = StartSessionRequest

// CleanupAgentSessionV2JSONRequestBody defines body for CleanupAgentSessionV2 for application/json ContentType.
type CleanupAgentSessionV2JSONRequestBody = CleanupAgentSessionV2Request

// GenerateAgentSessionTitleV2JSONRequestBody defines body for GenerateAgentSessionTitleV2 for application/json ContentType.
type GenerateAgentSessionTitleV2JSONRequestBody = GenerateTitleV2Request

// AsCleanupAgentSessionV2IncompleteResponse returns the union data inside the CleanupAgentSessionV2409JSONResponseBody as a CleanupAgentSessionV2IncompleteResponse
func (t CleanupAgentSessionV2409JSONResponseBody) AsCleanupAgentSessionV2IncompleteResponse() (CleanupAgentSessionV2IncompleteResponse, error) {
	var body CleanupAgentSessionV2IncompleteResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanupAgentSessionV2IncompleteResponse overwrites any union data inside the CleanupAgentSessionV2409JSONResponseBody as the provided CleanupAgentSessionV2IncompleteResponse
func (t *CleanupAgentSessionV2409JSONResponseBody) FromCleanupAgentSessionV2IncompleteResponse(v CleanupAgentSessionV2IncompleteResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanupAgentSessionV2IncompleteResponse performs a merge with any union data inside the CleanupAgentSessionV2409JSONResponseBody, using the provided CleanupAgentSessionV2IncompleteResponse
func (t *CleanupAgentSessionV2409JSONResponseBody) MergeCleanupAgentSessionV2IncompleteResponse(v CleanupAgentSessionV2IncompleteResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleanupOperationConflictError returns the union data inside the CleanupAgentSessionV2409JSONResponseBody as a CleanupOperationConflictError
func (t CleanupAgentSessionV2409JSONResponseBody) AsCleanupOperationConflictError() (CleanupOperationConflictError, error) {
	var body CleanupOperationConflictError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanupOperationConflictError overwrites any union data inside the CleanupAgentSessionV2409JSONResponseBody as the provided CleanupOperationConflictError
func (t *CleanupAgentSessionV2409JSONResponseBody) FromCleanupOperationConflictError(v CleanupOperationConflictError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanupOperationConflictError performs a merge with any union data inside the CleanupAgentSessionV2409JSONResponseBody, using the provided CleanupOperationConflictError
func (t *CleanupAgentSessionV2409JSONResponseBody) MergeCleanupOperationConflictError(v CleanupOperationConflictError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CleanupAgentSessionV2409JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CleanupAgentSessionV2409JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
