// Package agenthostcontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package agenthostcontract

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	LocalBearerScopes localBearerContextKey = "localBearer.Scopes"
)

// Defines values for AgentHostStatusRuntimeMode.
const (
	ManagedStdio AgentHostStatusRuntimeMode = "managed-stdio"
)

// Valid indicates whether the value is a known member of the AgentHostStatusRuntimeMode enum.
func (e AgentHostStatusRuntimeMode) Valid() bool {
	switch e {
	case ManagedStdio:
		return true
	default:
		return false
	}
}

// Defines values for AgentHostStatusService.
const (
	AgentHostStatusServiceYijieAgentHost AgentHostStatusService = "yijie-agent-host"
)

// Valid indicates whether the value is a known member of the AgentHostStatusService enum.
func (e AgentHostStatusService) Valid() bool {
	switch e {
	case AgentHostStatusServiceYijieAgentHost:
		return true
	default:
		return false
	}
}

// Defines values for AgentHostStatusStatus.
const (
	AgentHostStatusStatusDegraded AgentHostStatusStatus = "degraded"
	AgentHostStatusStatusOk       AgentHostStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the AgentHostStatusStatus enum.
func (e AgentHostStatusStatus) Valid() bool {
	switch e {
	case AgentHostStatusStatusDegraded:
		return true
	case AgentHostStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionFailureCode.
const (
	AgentSessionFailureCodeEmpty                       AgentSessionFailureCode = ""
	AgentSessionFailureCodeProviderIdentityMismatch    AgentSessionFailureCode = "provider_identity_mismatch"
	AgentSessionFailureCodeThreadResumeFailed          AgentSessionFailureCode = "thread_resume_failed"
	AgentSessionFailureCodeThreadResumeResponseInvalid AgentSessionFailureCode = "thread_resume_response_invalid"
	AgentSessionFailureCodeThreadStartFailed           AgentSessionFailureCode = "thread_start_failed"
	AgentSessionFailureCodeThreadStartResponseInvalid  AgentSessionFailureCode = "thread_start_response_invalid"
	AgentSessionFailureCodeTurnStartFailed             AgentSessionFailureCode = "turn_start_failed"
	AgentSessionFailureCodeTurnStartResponseInvalid    AgentSessionFailureCode = "turn_start_response_invalid"
)

// Valid indicates whether the value is a known member of the AgentSessionFailureCode enum.
func (e AgentSessionFailureCode) Valid() bool {
	switch e {
	case AgentSessionFailureCodeEmpty:
		return true
	case AgentSessionFailureCodeProviderIdentityMismatch:
		return true
	case AgentSessionFailureCodeThreadResumeFailed:
		return true
	case AgentSessionFailureCodeThreadResumeResponseInvalid:
		return true
	case AgentSessionFailureCodeThreadStartFailed:
		return true
	case AgentSessionFailureCodeThreadStartResponseInvalid:
		return true
	case AgentSessionFailureCodeTurnStartFailed:
		return true
	case AgentSessionFailureCodeTurnStartResponseInvalid:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionModel.
const (
	AgentSessionModelEmpty     AgentSessionModel = ""
	AgentSessionModelMiniMaxM3 AgentSessionModel = "MiniMax-M3"
)

// Valid indicates whether the value is a known member of the AgentSessionModel enum.
func (e AgentSessionModel) Valid() bool {
	switch e {
	case AgentSessionModelEmpty:
		return true
	case AgentSessionModelMiniMaxM3:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionModelProvider.
const (
	AgentSessionModelProviderEmpty   AgentSessionModelProvider = ""
	AgentSessionModelProviderMinimax AgentSessionModelProvider = "minimax"
)

// Valid indicates whether the value is a known member of the AgentSessionModelProvider enum.
func (e AgentSessionModelProvider) Valid() bool {
	switch e {
	case AgentSessionModelProviderEmpty:
		return true
	case AgentSessionModelProviderMinimax:
		return true
	default:
		return false
	}
}

// Defines values for AgentSessionState.
const (
	AgentSessionStateActive   AgentSessionState = "active"
	AgentSessionStateFailed   AgentSessionState = "failed"
	AgentSessionStateIdle     AgentSessionState = "idle"
	AgentSessionStateStarting AgentSessionState = "starting"
)

// Valid indicates whether the value is a known member of the AgentSessionState enum.
func (e AgentSessionState) Valid() bool {
	switch e {
	case AgentSessionStateActive:
		return true
	case AgentSessionStateFailed:
		return true
	case AgentSessionStateIdle:
		return true
	case AgentSessionStateStarting:
		return true
	default:
		return false
	}
}

// Defines values for ArtifactAcknowledgementV3ResponseCleanupStatus.
const (
	Completed ArtifactAcknowledgementV3ResponseCleanupStatus = "completed"
	Pending   ArtifactAcknowledgementV3ResponseCleanupStatus = "pending"
)

// Valid indicates whether the value is a known member of the ArtifactAcknowledgementV3ResponseCleanupStatus enum.
func (e ArtifactAcknowledgementV3ResponseCleanupStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ArtifactAcknowledgementV3ResponseStatus.
const (
	Acknowledged ArtifactAcknowledgementV3ResponseStatus = "acknowledged"
)

// Valid indicates whether the value is a known member of the ArtifactAcknowledgementV3ResponseStatus enum.
func (e ArtifactAcknowledgementV3ResponseStatus) Valid() bool {
	switch e {
	case Acknowledged:
		return true
	default:
		return false
	}
}

// Defines values for ArtifactErrorResponseV3ErrorCode.
const (
	ArtifactErrorResponseV3ErrorCodeArtifactAckConflict         ArtifactErrorResponseV3ErrorCode = "artifact_ack_conflict"
	ArtifactErrorResponseV3ErrorCodeArtifactExpired             ArtifactErrorResponseV3ErrorCode = "artifact_expired"
	ArtifactErrorResponseV3ErrorCodeArtifactManifestMismatch    ArtifactErrorResponseV3ErrorCode = "artifact_manifest_mismatch"
	ArtifactErrorResponseV3ErrorCodeArtifactNotFound            ArtifactErrorResponseV3ErrorCode = "artifact_not_found"
	ArtifactErrorResponseV3ErrorCodeArtifactNotReady            ArtifactErrorResponseV3ErrorCode = "artifact_not_ready"
	ArtifactErrorResponseV3ErrorCodeArtifactRangeNotSatisfiable ArtifactErrorResponseV3ErrorCode = "artifact_range_not_satisfiable"
	ArtifactErrorResponseV3ErrorCodeArtifactResourceUnavailable ArtifactErrorResponseV3ErrorCode = "artifact_resource_unavailable"
	ArtifactErrorResponseV3ErrorCodeInternalError               ArtifactErrorResponseV3ErrorCode = "internal_error"
	ArtifactErrorResponseV3ErrorCodeInvalidRange                ArtifactErrorResponseV3ErrorCode = "invalid_range"
	ArtifactErrorResponseV3ErrorCodeInvalidRequest              ArtifactErrorResponseV3ErrorCode = "invalid_request"
	ArtifactErrorResponseV3ErrorCodeUnauthorized                ArtifactErrorResponseV3ErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ArtifactErrorResponseV3ErrorCode enum.
func (e ArtifactErrorResponseV3ErrorCode) Valid() bool {
	switch e {
	case ArtifactErrorResponseV3ErrorCodeArtifactAckConflict:
		return true
	case ArtifactErrorResponseV3ErrorCodeArtifactExpired:
		return true
	case ArtifactErrorResponseV3ErrorCodeArtifactManifestMismatch:
		return true
	case ArtifactErrorResponseV3ErrorCodeArtifactNotFound:
		return true
	case ArtifactErrorResponseV3ErrorCodeArtifactNotReady:
		return true
	case ArtifactErrorResponseV3ErrorCodeArtifactRangeNotSatisfiable:
		return true
	case ArtifactErrorResponseV3ErrorCodeArtifactResourceUnavailable:
		return true
	case ArtifactErrorResponseV3ErrorCodeInternalError:
		return true
	case ArtifactErrorResponseV3ErrorCodeInvalidRange:
		return true
	case ArtifactErrorResponseV3ErrorCodeInvalidRequest:
		return true
	case ArtifactErrorResponseV3ErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for CleanupAgentSessionV2CompletedResponseOutcome.
const (
	CleanupAgentSessionV2CompletedResponseOutcomeComplete CleanupAgentSessionV2CompletedResponseOutcome = "complete"
)

// Valid indicates whether the value is a known member of the CleanupAgentSessionV2CompletedResponseOutcome enum.
func (e CleanupAgentSessionV2CompletedResponseOutcome) Valid() bool {
	switch e {
	case CleanupAgentSessionV2CompletedResponseOutcomeComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupAgentSessionV2IncompleteResponseOutcome.
const (
	CleanupAgentSessionV2IncompleteResponseOutcomeIncomplete CleanupAgentSessionV2IncompleteResponseOutcome = "incomplete"
)

// Valid indicates whether the value is a known member of the CleanupAgentSessionV2IncompleteResponseOutcome enum.
func (e CleanupAgentSessionV2IncompleteResponseOutcome) Valid() bool {
	switch e {
	case CleanupAgentSessionV2IncompleteResponseOutcomeIncomplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupCompletedSurfacesHostMapping.
const (
	CleanupCompletedSurfacesHostMappingComplete CleanupCompletedSurfacesHostMapping = "complete"
)

// Valid indicates whether the value is a known member of the CleanupCompletedSurfacesHostMapping enum.
func (e CleanupCompletedSurfacesHostMapping) Valid() bool {
	switch e {
	case CleanupCompletedSurfacesHostMappingComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupCompletedSurfacesHostReplay.
const (
	CleanupCompletedSurfacesHostReplayComplete CleanupCompletedSurfacesHostReplay = "complete"
)

// Valid indicates whether the value is a known member of the CleanupCompletedSurfacesHostReplay enum.
func (e CleanupCompletedSurfacesHostReplay) Valid() bool {
	switch e {
	case CleanupCompletedSurfacesHostReplayComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupCompletedSurfacesRuntimeThreadTree.
const (
	CleanupCompletedSurfacesRuntimeThreadTreeComplete CleanupCompletedSurfacesRuntimeThreadTree = "complete"
)

// Valid indicates whether the value is a known member of the CleanupCompletedSurfacesRuntimeThreadTree enum.
func (e CleanupCompletedSurfacesRuntimeThreadTree) Valid() bool {
	switch e {
	case CleanupCompletedSurfacesRuntimeThreadTreeComplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupIncompleteErrorCode.
const (
	CleanupIncomplete CleanupIncompleteErrorCode = "cleanup_incomplete"
)

// Valid indicates whether the value is a known member of the CleanupIncompleteErrorCode enum.
func (e CleanupIncompleteErrorCode) Valid() bool {
	switch e {
	case CleanupIncomplete:
		return true
	default:
		return false
	}
}

// Defines values for CleanupIncompleteErrorReasonCode.
const (
	CleanupIncompleteErrorReasonCodeActiveTurn                CleanupIncompleteErrorReasonCode = "active_turn"
	CleanupIncompleteErrorReasonCodeHostMappingCleanupFailed  CleanupIncompleteErrorReasonCode = "host_mapping_cleanup_failed"
	CleanupIncompleteErrorReasonCodeHostReplayCleanupFailed   CleanupIncompleteErrorReasonCode = "host_replay_cleanup_failed"
	CleanupIncompleteErrorReasonCodeInternalError             CleanupIncompleteErrorReasonCode = "internal_error"
	CleanupIncompleteErrorReasonCodeOperationStateUnavailable CleanupIncompleteErrorReasonCode = "operation_state_unavailable"
	CleanupIncompleteErrorReasonCodeRuntimeDeleteFailed       CleanupIncompleteErrorReasonCode = "runtime_delete_failed"
	CleanupIncompleteErrorReasonCodeRuntimeDeleteUnconfirmed  CleanupIncompleteErrorReasonCode = "runtime_delete_unconfirmed"
	CleanupIncompleteErrorReasonCodeSharedThreadMapping       CleanupIncompleteErrorReasonCode = "shared_thread_mapping"
	CleanupIncompleteErrorReasonCodeTerminalUnconfirmed       CleanupIncompleteErrorReasonCode = "terminal_unconfirmed"
)

// Valid indicates whether the value is a known member of the CleanupIncompleteErrorReasonCode enum.
func (e CleanupIncompleteErrorReasonCode) Valid() bool {
	switch e {
	case CleanupIncompleteErrorReasonCodeActiveTurn:
		return true
	case CleanupIncompleteErrorReasonCodeHostMappingCleanupFailed:
		return true
	case CleanupIncompleteErrorReasonCodeHostReplayCleanupFailed:
		return true
	case CleanupIncompleteErrorReasonCodeInternalError:
		return true
	case CleanupIncompleteErrorReasonCodeOperationStateUnavailable:
		return true
	case CleanupIncompleteErrorReasonCodeRuntimeDeleteFailed:
		return true
	case CleanupIncompleteErrorReasonCodeRuntimeDeleteUnconfirmed:
		return true
	case CleanupIncompleteErrorReasonCodeSharedThreadMapping:
		return true
	case CleanupIncompleteErrorReasonCodeTerminalUnconfirmed:
		return true
	default:
		return false
	}
}

// Defines values for CleanupOperationConflictErrorErrorCode.
const (
	CleanupOperationConflict CleanupOperationConflictErrorErrorCode = "cleanup_operation_conflict"
)

// Valid indicates whether the value is a known member of the CleanupOperationConflictErrorErrorCode enum.
func (e CleanupOperationConflictErrorErrorCode) Valid() bool {
	switch e {
	case CleanupOperationConflict:
		return true
	default:
		return false
	}
}

// Defines values for CleanupSurfaceStatus.
const (
	CleanupSurfaceStatusComplete     CleanupSurfaceStatus = "complete"
	CleanupSurfaceStatusIncomplete   CleanupSurfaceStatus = "incomplete"
	CleanupSurfaceStatusNotAttempted CleanupSurfaceStatus = "not_attempted"
)

// Valid indicates whether the value is a known member of the CleanupSurfaceStatus enum.
func (e CleanupSurfaceStatus) Valid() bool {
	switch e {
	case CleanupSurfaceStatusComplete:
		return true
	case CleanupSurfaceStatusIncomplete:
		return true
	case CleanupSurfaceStatusNotAttempted:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ErrorResponseErrorCodeEventReplayUnavailable ErrorResponseErrorCode = "event_replay_unavailable"
	ErrorResponseErrorCodeEventStreamChanged     ErrorResponseErrorCode = "event_stream_changed"
	ErrorResponseErrorCodeInternalError          ErrorResponseErrorCode = "internal_error"
	ErrorResponseErrorCodeInvalidEventCursor     ErrorResponseErrorCode = "invalid_event_cursor"
	ErrorResponseErrorCodeInvalidRequest         ErrorResponseErrorCode = "invalid_request"
	ErrorResponseErrorCodeRuntimeRequestFailed   ErrorResponseErrorCode = "runtime_request_failed"
	ErrorResponseErrorCodeSessionNotFound        ErrorResponseErrorCode = "session_not_found"
	ErrorResponseErrorCodeSessionNotUsable       ErrorResponseErrorCode = "session_not_usable"
	ErrorResponseErrorCodeStreamingUnsupported   ErrorResponseErrorCode = "streaming_unsupported"
	ErrorResponseErrorCodeTaskSessionExists      ErrorResponseErrorCode = "task_session_exists"
	ErrorResponseErrorCodeTurnActive             ErrorResponseErrorCode = "turn_active"
	ErrorResponseErrorCodeTurnNotActive          ErrorResponseErrorCode = "turn_not_active"
	ErrorResponseErrorCodeUnauthorized           ErrorResponseErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ErrorResponseErrorCodeEventReplayUnavailable:
		return true
	case ErrorResponseErrorCodeEventStreamChanged:
		return true
	case ErrorResponseErrorCodeInternalError:
		return true
	case ErrorResponseErrorCodeInvalidEventCursor:
		return true
	case ErrorResponseErrorCodeInvalidRequest:
		return true
	case ErrorResponseErrorCodeRuntimeRequestFailed:
		return true
	case ErrorResponseErrorCodeSessionNotFound:
		return true
	case ErrorResponseErrorCodeSessionNotUsable:
		return true
	case ErrorResponseErrorCodeStreamingUnsupported:
		return true
	case ErrorResponseErrorCodeTaskSessionExists:
		return true
	case ErrorResponseErrorCodeTurnActive:
		return true
	case ErrorResponseErrorCodeTurnNotActive:
		return true
	case ErrorResponseErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseService.
const (
	HealthResponseServiceYijieAgentHost HealthResponseService = "yijie-agent-host"
)

// Valid indicates whether the value is a known member of the HealthResponseService enum.
func (e HealthResponseService) Valid() bool {
	switch e {
	case HealthResponseServiceYijieAgentHost:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ManagedSkillCapabilityReadiness.
const (
	ManagedSkillCapabilityReadinessBlocked  ManagedSkillCapabilityReadiness = "blocked"
	ManagedSkillCapabilityReadinessDegraded ManagedSkillCapabilityReadiness = "degraded"
	ManagedSkillCapabilityReadinessReady    ManagedSkillCapabilityReadiness = "ready"
)

// Valid indicates whether the value is a known member of the ManagedSkillCapabilityReadiness enum.
func (e ManagedSkillCapabilityReadiness) Valid() bool {
	switch e {
	case ManagedSkillCapabilityReadinessBlocked:
		return true
	case ManagedSkillCapabilityReadinessDegraded:
		return true
	case ManagedSkillCapabilityReadinessReady:
		return true
	default:
		return false
	}
}

// Defines values for ManagedSkillCatalogBlockedReason.
const (
	CapabilityUnavailable     ManagedSkillCatalogBlockedReason = "capability_unavailable"
	DistributionNotAuthorized ManagedSkillCatalogBlockedReason = "distribution_not_authorized"
	LicenseUnverified         ManagedSkillCatalogBlockedReason = "license_unverified"
	MaintenanceEnded          ManagedSkillCatalogBlockedReason = "maintenance_ended"
	SecurityReviewPending     ManagedSkillCatalogBlockedReason = "security_review_pending"
	SourceUnverified          ManagedSkillCatalogBlockedReason = "source_unverified"
)

// Valid indicates whether the value is a known member of the ManagedSkillCatalogBlockedReason enum.
func (e ManagedSkillCatalogBlockedReason) Valid() bool {
	switch e {
	case CapabilityUnavailable:
		return true
	case DistributionNotAuthorized:
		return true
	case LicenseUnverified:
		return true
	case MaintenanceEnded:
		return true
	case SecurityReviewPending:
		return true
	case SourceUnverified:
		return true
	default:
		return false
	}
}

// Defines values for ManagedSkillCatalogStatus.
const (
	ManagedSkillCatalogStatusBlocked     ManagedSkillCatalogStatus = "blocked"
	ManagedSkillCatalogStatusInstallable ManagedSkillCatalogStatus = "installable"
)

// Valid indicates whether the value is a known member of the ManagedSkillCatalogStatus enum.
func (e ManagedSkillCatalogStatus) Valid() bool {
	switch e {
	case ManagedSkillCatalogStatusBlocked:
		return true
	case ManagedSkillCatalogStatusInstallable:
		return true
	default:
		return false
	}
}

// Defines values for ManagedSkillFailureCode.
const (
	ManagedSkillFailureCodeArchiveChecksumMismatch ManagedSkillFailureCode = "archive_checksum_mismatch"
	ManagedSkillFailureCodeArchiveTooLarge         ManagedSkillFailureCode = "archive_too_large"
	ManagedSkillFailureCodeArchiveUnsafe           ManagedSkillFailureCode = "archive_unsafe"
	ManagedSkillFailureCodeBundleManifestInvalid   ManagedSkillFailureCode = "bundle_manifest_invalid"
	ManagedSkillFailureCodeBundleMissing           ManagedSkillFailureCode = "bundle_missing"
	ManagedSkillFailureCodeCapabilityUnavailable   ManagedSkillFailureCode = "capability_unavailable"
	ManagedSkillFailureCodeEmpty                   ManagedSkillFailureCode = ""
	ManagedSkillFailureCodeInstallFailed           ManagedSkillFailureCode = "install_failed"
	ManagedSkillFailureCodeInstallReceiptInvalid   ManagedSkillFailureCode = "install_receipt_invalid"
	ManagedSkillFailureCodeInstalledFilesCorrupt   ManagedSkillFailureCode = "installed_files_corrupt"
	ManagedSkillFailureCodeInstalledFilesMissing   ManagedSkillFailureCode = "installed_files_missing"
	ManagedSkillFailureCodeRuntimeSyncFailed       ManagedSkillFailureCode = "runtime_sync_failed"
	ManagedSkillFailureCodeRuntimeUnavailable      ManagedSkillFailureCode = "runtime_unavailable"
	ManagedSkillFailureCodeScanFailed              ManagedSkillFailureCode = "scan_failed"
	ManagedSkillFailureCodeUninstallFailed         ManagedSkillFailureCode = "uninstall_failed"
)

// Valid indicates whether the value is a known member of the ManagedSkillFailureCode enum.
func (e ManagedSkillFailureCode) Valid() bool {
	switch e {
	case ManagedSkillFailureCodeArchiveChecksumMismatch:
		return true
	case ManagedSkillFailureCodeArchiveTooLarge:
		return true
	case ManagedSkillFailureCodeArchiveUnsafe:
		return true
	case ManagedSkillFailureCodeBundleManifestInvalid:
		return true
	case ManagedSkillFailureCodeBundleMissing:
		return true
	case ManagedSkillFailureCodeCapabilityUnavailable:
		return true
	case ManagedSkillFailureCodeEmpty:
		return true
	case ManagedSkillFailureCodeInstallFailed:
		return true
	case ManagedSkillFailureCodeInstallReceiptInvalid:
		return true
	case ManagedSkillFailureCodeInstalledFilesCorrupt:
		return true
	case ManagedSkillFailureCodeInstalledFilesMissing:
		return true
	case ManagedSkillFailureCodeRuntimeSyncFailed:
		return true
	case ManagedSkillFailureCodeRuntimeUnavailable:
		return true
	case ManagedSkillFailureCodeScanFailed:
		return true
	case ManagedSkillFailureCodeUninstallFailed:
		return true
	default:
		return false
	}
}

// Defines values for ManagedSkillInstallationStatus.
const (
	Error        ManagedSkillInstallationStatus = "error"
	Installed    ManagedSkillInstallationStatus = "installed"
	Installing   ManagedSkillInstallationStatus = "installing"
	NotInstalled ManagedSkillInstallationStatus = "not_installed"
	Uninstalling ManagedSkillInstallationStatus = "uninstalling"
)

// Valid indicates whether the value is a known member of the ManagedSkillInstallationStatus enum.
func (e ManagedSkillInstallationStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Installed:
		return true
	case Installing:
		return true
	case NotInstalled:
		return true
	case Uninstalling:
		return true
	default:
		return false
	}
}

// Defines values for ManagedSkillMaintenanceStatus.
const (
	Maintained   ManagedSkillMaintenanceStatus = "maintained"
	Unmaintained ManagedSkillMaintenanceStatus = "unmaintained"
)

// Valid indicates whether the value is a known member of the ManagedSkillMaintenanceStatus enum.
func (e ManagedSkillMaintenanceStatus) Valid() bool {
	switch e {
	case Maintained:
		return true
	case Unmaintained:
		return true
	default:
		return false
	}
}

// Defines values for NotReadyResponseStatus.
const (
	NotReady NotReadyResponseStatus = "not_ready"
)

// Valid indicates whether the value is a known member of the NotReadyResponseStatus enum.
func (e NotReadyResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseRuntimeState.
const (
	ReadyResponseRuntimeStateReady ReadyResponseRuntimeState = "ready"
)

// Valid indicates whether the value is a known member of the ReadyResponseRuntimeState enum.
func (e ReadyResponseRuntimeState) Valid() bool {
	switch e {
	case ReadyResponseRuntimeStateReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseStatus.
const (
	ReadyResponseStatusReady ReadyResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyResponseStatus enum.
func (e ReadyResponseStatus) Valid() bool {
	switch e {
	case ReadyResponseStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeState.
const (
	RuntimeStateFailed        RuntimeState = "failed"
	RuntimeStateInitializing  RuntimeState = "initializing"
	RuntimeStateNotConfigured RuntimeState = "not_configured"
	RuntimeStateReady         RuntimeState = "ready"
	RuntimeStateStarting      RuntimeState = "starting"
	RuntimeStateStopped       RuntimeState = "stopped"
	RuntimeStateStopping      RuntimeState = "stopping"
	RuntimeStateVerifying     RuntimeState = "verifying"
)

// Valid indicates whether the value is a known member of the RuntimeState enum.
func (e RuntimeState) Valid() bool {
	switch e {
	case RuntimeStateFailed:
		return true
	case RuntimeStateInitializing:
		return true
	case RuntimeStateNotConfigured:
		return true
	case RuntimeStateReady:
		return true
	case RuntimeStateStarting:
		return true
	case RuntimeStateStopped:
		return true
	case RuntimeStateStopping:
		return true
	case RuntimeStateVerifying:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusExperimentalApi.
const (
	False RuntimeStatusExperimentalApi = false
)

// Valid indicates whether the value is a known member of the RuntimeStatusExperimentalApi enum.
func (e RuntimeStatusExperimentalApi) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusFailureCode.
const (
	ArtifactVerificationFailed    RuntimeStatusFailureCode = "artifact_verification_failed"
	InitializeFailed              RuntimeStatusFailureCode = "initialize_failed"
	InitializeResponseInvalid     RuntimeStatusFailureCode = "initialize_response_invalid"
	InitializedNotificationFailed RuntimeStatusFailureCode = "initialized_notification_failed"
	ProtocolFailure               RuntimeStatusFailureCode = "protocol_failure"
	ProviderConfigFailed          RuntimeStatusFailureCode = "provider_config_failed"
	RuntimeConfigInvalid          RuntimeStatusFailureCode = "runtime_config_invalid"
	RuntimeDisconnected           RuntimeStatusFailureCode = "runtime_disconnected"
	RuntimeExited                 RuntimeStatusFailureCode = "runtime_exited"
	RuntimeNotConfigured          RuntimeStatusFailureCode = "runtime_not_configured"
	RuntimeStartFailed            RuntimeStatusFailureCode = "runtime_start_failed"
	StartupCancelled              RuntimeStatusFailureCode = "startup_cancelled"
)

// Valid indicates whether the value is a known member of the RuntimeStatusFailureCode enum.
func (e RuntimeStatusFailureCode) Valid() bool {
	switch e {
	case ArtifactVerificationFailed:
		return true
	case InitializeFailed:
		return true
	case InitializeResponseInvalid:
		return true
	case InitializedNotificationFailed:
		return true
	case ProtocolFailure:
		return true
	case ProviderConfigFailed:
		return true
	case RuntimeConfigInvalid:
		return true
	case RuntimeDisconnected:
		return true
	case RuntimeExited:
		return true
	case RuntimeNotConfigured:
		return true
	case RuntimeStartFailed:
		return true
	case StartupCancelled:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusModel.
const (
	MiniMaxM3 RuntimeStatusModel = "MiniMax-M3"
)

// Valid indicates whether the value is a known member of the RuntimeStatusModel enum.
func (e RuntimeStatusModel) Valid() bool {
	switch e {
	case MiniMaxM3:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusModelProvider.
const (
	Minimax RuntimeStatusModelProvider = "minimax"
)

// Valid indicates whether the value is a known member of the RuntimeStatusModelProvider enum.
func (e RuntimeStatusModelProvider) Valid() bool {
	switch e {
	case Minimax:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusRuntimeVersion.
const (
	N01446 RuntimeStatusRuntimeVersion = "0.144.6"
)

// Valid indicates whether the value is a known member of the RuntimeStatusRuntimeVersion enum.
func (e RuntimeStatusRuntimeVersion) Valid() bool {
	switch e {
	case N01446:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusTransport.
const (
	Stdio RuntimeStatusTransport = "stdio"
)

// Valid indicates whether the value is a known member of the RuntimeStatusTransport enum.
func (e RuntimeStatusTransport) Valid() bool {
	switch e {
	case Stdio:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusUpstreamCommit.
const (
	N5d1fbf26c43abc65a203928b2e31561cb039e06d RuntimeStatusUpstreamCommit = "5d1fbf26c43abc65a203928b2e31561cb039e06d"
)

// Valid indicates whether the value is a known member of the RuntimeStatusUpstreamCommit enum.
func (e RuntimeStatusUpstreamCommit) Valid() bool {
	switch e {
	case N5d1fbf26c43abc65a203928b2e31561cb039e06d:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusUpstreamTag.
const (
	RustV01446 RuntimeStatusUpstreamTag = "rust-v0.144.6"
)

// Valid indicates whether the value is a known member of the RuntimeStatusUpstreamTag enum.
func (e RuntimeStatusUpstreamTag) Valid() bool {
	switch e {
	case RustV01446:
		return true
	default:
		return false
	}
}

// Defines values for SkillErrorResponseErrorCode.
const (
	SkillErrorResponseErrorCodeArchiveChecksumMismatch SkillErrorResponseErrorCode = "archive_checksum_mismatch"
	SkillErrorResponseErrorCodeArchiveTooLarge         SkillErrorResponseErrorCode = "archive_too_large"
	SkillErrorResponseErrorCodeArchiveUnsafe           SkillErrorResponseErrorCode = "archive_unsafe"
	SkillErrorResponseErrorCodeBundleManifestInvalid   SkillErrorResponseErrorCode = "bundle_manifest_invalid"
	SkillErrorResponseErrorCodeBundleMissing           SkillErrorResponseErrorCode = "bundle_missing"
	SkillErrorResponseErrorCodeCapabilityDenied        SkillErrorResponseErrorCode = "capability_denied"
	SkillErrorResponseErrorCodeInstallFailed           SkillErrorResponseErrorCode = "install_failed"
	SkillErrorResponseErrorCodeInternalError           SkillErrorResponseErrorCode = "internal_error"
	SkillErrorResponseErrorCodeInvalidRequest          SkillErrorResponseErrorCode = "invalid_request"
	SkillErrorResponseErrorCodeRuntimeSyncFailed       SkillErrorResponseErrorCode = "runtime_sync_failed"
	SkillErrorResponseErrorCodeRuntimeUnavailable      SkillErrorResponseErrorCode = "runtime_unavailable"
	SkillErrorResponseErrorCodeScanFailed              SkillErrorResponseErrorCode = "scan_failed"
	SkillErrorResponseErrorCodeSkillBusy               SkillErrorResponseErrorCode = "skill_busy"
	SkillErrorResponseErrorCodeSkillNotFound           SkillErrorResponseErrorCode = "skill_not_found"
	SkillErrorResponseErrorCodeSkillNotInstallable     SkillErrorResponseErrorCode = "skill_not_installable"
	SkillErrorResponseErrorCodeSkillOperationConflict  SkillErrorResponseErrorCode = "skill_operation_conflict"
	SkillErrorResponseErrorCodeUnauthorized            SkillErrorResponseErrorCode = "unauthorized"
	SkillErrorResponseErrorCodeUninstallFailed         SkillErrorResponseErrorCode = "uninstall_failed"
)

// Valid indicates whether the value is a known member of the SkillErrorResponseErrorCode enum.
func (e SkillErrorResponseErrorCode) Valid() bool {
	switch e {
	case SkillErrorResponseErrorCodeArchiveChecksumMismatch:
		return true
	case SkillErrorResponseErrorCodeArchiveTooLarge:
		return true
	case SkillErrorResponseErrorCodeArchiveUnsafe:
		return true
	case SkillErrorResponseErrorCodeBundleManifestInvalid:
		return true
	case SkillErrorResponseErrorCodeBundleMissing:
		return true
	case SkillErrorResponseErrorCodeCapabilityDenied:
		return true
	case SkillErrorResponseErrorCodeInstallFailed:
		return true
	case SkillErrorResponseErrorCodeInternalError:
		return true
	case SkillErrorResponseErrorCodeInvalidRequest:
		return true
	case SkillErrorResponseErrorCodeRuntimeSyncFailed:
		return true
	case SkillErrorResponseErrorCodeRuntimeUnavailable:
		return true
	case SkillErrorResponseErrorCodeScanFailed:
		return true
	case SkillErrorResponseErrorCodeSkillBusy:
		return true
	case SkillErrorResponseErrorCodeSkillNotFound:
		return true
	case SkillErrorResponseErrorCodeSkillNotInstallable:
		return true
	case SkillErrorResponseErrorCodeSkillOperationConflict:
		return true
	case SkillErrorResponseErrorCodeUnauthorized:
		return true
	case SkillErrorResponseErrorCodeUninstallFailed:
		return true
	default:
		return false
	}
}

// Defines values for SkillListResponseSchemaVersion.
const (
	N1 SkillListResponseSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the SkillListResponseSchemaVersion enum.
func (e SkillListResponseSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for SkillMutationResponseOutcome.
const (
	SkillMutationResponseOutcomeComplete SkillMutationResponseOutcome = "complete"
)

// Valid indicates whether the value is a known member of the SkillMutationResponseOutcome enum.
func (e SkillMutationResponseOutcome) Valid() bool {
	switch e {
	case SkillMutationResponseOutcomeComplete:
		return true
	default:
		return false
	}
}

// Defines values for SkillScanRequestReason.
const (
	AppUpgrade       SkillScanRequestReason = "app_upgrade"
	DirectoryChanged SkillScanRequestReason = "directory_changed"
	PageOpen         SkillScanRequestReason = "page_open"
	Startup          SkillScanRequestReason = "startup"
	UserRetry        SkillScanRequestReason = "user_retry"
	WindowResume     SkillScanRequestReason = "window_resume"
)

// Valid indicates whether the value is a known member of the SkillScanRequestReason enum.
func (e SkillScanRequestReason) Valid() bool {
	switch e {
	case AppUpgrade:
		return true
	case DirectoryChanged:
		return true
	case PageOpen:
		return true
	case Startup:
		return true
	case UserRetry:
		return true
	case WindowResume:
		return true
	default:
		return false
	}
}

// Defines values for SkillScanResponseOutcome.
const (
	SkillScanResponseOutcomeComplete SkillScanResponseOutcome = "complete"
)

// Valid indicates whether the value is a known member of the SkillScanResponseOutcome enum.
func (e SkillScanResponseOutcome) Valid() bool {
	switch e {
	case SkillScanResponseOutcomeComplete:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnRequestReasoningEffort.
const (
	Empty StartTurnRequestReasoningEffort = ""
	High  StartTurnRequestReasoningEffort = "high"
	None  StartTurnRequestReasoningEffort = "none"
)

// Valid indicates whether the value is a known member of the StartTurnRequestReasoningEffort enum.
func (e StartTurnRequestReasoningEffort) Valid() bool {
	switch e {
	case Empty:
		return true
	case High:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnV2FileBlockType.
const (
	StartTurnV2ContentTypeFile StartTurnV2FileBlockType = "file"
)

// Valid indicates whether the value is a known member of the StartTurnV2FileBlockType enum.
func (e StartTurnV2FileBlockType) Valid() bool {
	switch e {
	case StartTurnV2ContentTypeFile:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnV2FileMediaType.
const (
	StartTurnV2FileMediaTypeCSV       StartTurnV2FileMediaType = "text/csv"
	StartTurnV2FileMediaTypeDOCX      StartTurnV2FileMediaType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	StartTurnV2FileMediaTypeHTML      StartTurnV2FileMediaType = "text/html"
	StartTurnV2FileMediaTypeJSON      StartTurnV2FileMediaType = "application/json"
	StartTurnV2FileMediaTypeMarkdown  StartTurnV2FileMediaType = "text/markdown"
	StartTurnV2FileMediaTypePDF       StartTurnV2FileMediaType = "application/pdf"
	StartTurnV2FileMediaTypePPTX      StartTurnV2FileMediaType = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	StartTurnV2FileMediaTypePlainText StartTurnV2FileMediaType = "text/plain"
	StartTurnV2FileMediaTypeRTF       StartTurnV2FileMediaType = "application/rtf"
	StartTurnV2FileMediaTypeXLSX      StartTurnV2FileMediaType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	StartTurnV2FileMediaTypeXML       StartTurnV2FileMediaType = "application/xml"
	StartTurnV2FileMediaTypeYAML      StartTurnV2FileMediaType = "application/yaml"
)

// Valid indicates whether the value is a known member of the StartTurnV2FileMediaType enum.
func (e StartTurnV2FileMediaType) Valid() bool {
	switch e {
	case StartTurnV2FileMediaTypeCSV:
		return true
	case StartTurnV2FileMediaTypeDOCX:
		return true
	case StartTurnV2FileMediaTypeHTML:
		return true
	case StartTurnV2FileMediaTypeJSON:
		return true
	case StartTurnV2FileMediaTypeMarkdown:
		return true
	case StartTurnV2FileMediaTypePDF:
		return true
	case StartTurnV2FileMediaTypePPTX:
		return true
	case StartTurnV2FileMediaTypePlainText:
		return true
	case StartTurnV2FileMediaTypeRTF:
		return true
	case StartTurnV2FileMediaTypeXLSX:
		return true
	case StartTurnV2FileMediaTypeXML:
		return true
	case StartTurnV2FileMediaTypeYAML:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnV2ImageBlockMediaType.
const (
	StartTurnV2ImageMediaTypeGIF  StartTurnV2ImageBlockMediaType = "image/gif"
	StartTurnV2ImageMediaTypeJPEG StartTurnV2ImageBlockMediaType = "image/jpeg"
	StartTurnV2ImageMediaTypePNG  StartTurnV2ImageBlockMediaType = "image/png"
	StartTurnV2ImageMediaTypeWebP StartTurnV2ImageBlockMediaType = "image/webp"
)

// Valid indicates whether the value is a known member of the StartTurnV2ImageBlockMediaType enum.
func (e StartTurnV2ImageBlockMediaType) Valid() bool {
	switch e {
	case StartTurnV2ImageMediaTypeGIF:
		return true
	case StartTurnV2ImageMediaTypeJPEG:
		return true
	case StartTurnV2ImageMediaTypePNG:
		return true
	case StartTurnV2ImageMediaTypeWebP:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnV2ImageBlockType.
const (
	StartTurnV2ContentTypeImage StartTurnV2ImageBlockType = "image"
)

// Valid indicates whether the value is a known member of the StartTurnV2ImageBlockType enum.
func (e StartTurnV2ImageBlockType) Valid() bool {
	switch e {
	case StartTurnV2ContentTypeImage:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnV2RequestReasoningEffort.
const (
	StartTurnV2ReasoningEffortEmpty StartTurnV2RequestReasoningEffort = ""
	StartTurnV2ReasoningEffortHigh  StartTurnV2RequestReasoningEffort = "high"
	StartTurnV2ReasoningEffortNone  StartTurnV2RequestReasoningEffort = "none"
)

// Valid indicates whether the value is a known member of the StartTurnV2RequestReasoningEffort enum.
func (e StartTurnV2RequestReasoningEffort) Valid() bool {
	switch e {
	case StartTurnV2ReasoningEffortEmpty:
		return true
	case StartTurnV2ReasoningEffortHigh:
		return true
	case StartTurnV2ReasoningEffortNone:
		return true
	default:
		return false
	}
}

// Defines values for StartTurnV2TextBlockType.
const (
	StartTurnV2ContentTypeText StartTurnV2TextBlockType = "text"
)

// Valid indicates whether the value is a known member of the StartTurnV2TextBlockType enum.
func (e StartTurnV2TextBlockType) Valid() bool {
	switch e {
	case StartTurnV2ContentTypeText:
		return true
	default:
		return false
	}
}

// Defines values for TitleGenerationUnavailableErrorErrorCode.
const (
	TitleGenerationUnavailableErrorErrorCodeTitleGenerationUnavailable TitleGenerationUnavailableErrorErrorCode = "title_generation_unavailable"
)

// Valid indicates whether the value is a known member of the TitleGenerationUnavailableErrorErrorCode enum.
func (e TitleGenerationUnavailableErrorErrorCode) Valid() bool {
	switch e {
	case TitleGenerationUnavailableErrorErrorCodeTitleGenerationUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for TitleOperationConflictErrorErrorCode.
const (
	TitleOperationConflictErrorErrorCodeTitleOperationConflict TitleOperationConflictErrorErrorCode = "title_operation_conflict"
)

// Valid indicates whether the value is a known member of the TitleOperationConflictErrorErrorCode enum.
func (e TitleOperationConflictErrorErrorCode) Valid() bool {
	switch e {
	case TitleOperationConflictErrorErrorCodeTitleOperationConflict:
		return true
	default:
		return false
	}
}

// Defines values for TitleOutputInvalidErrorErrorCode.
const (
	TitleOutputInvalidErrorErrorCodeTitleOutputInvalid TitleOutputInvalidErrorErrorCode = "title_output_invalid"
)

// Valid indicates whether the value is a known member of the TitleOutputInvalidErrorErrorCode enum.
func (e TitleOutputInvalidErrorErrorCode) Valid() bool {
	switch e {
	case TitleOutputInvalidErrorErrorCodeTitleOutputInvalid:
		return true
	default:
		return false
	}
}

// Defines values for TurnOperationConflictErrorErrorCode.
const (
	TurnOperationConflict TurnOperationConflictErrorErrorCode = "turn_operation_conflict"
)

// Valid indicates whether the value is a known member of the TurnOperationConflictErrorErrorCode enum.
func (e TurnOperationConflictErrorErrorCode) Valid() bool {
	switch e {
	case TurnOperationConflict:
		return true
	default:
		return false
	}
}

// Defines values for EventSchemaVersionV2.
const (
	EventSchemaVersionV2N2 EventSchemaVersionV2 = 2
)

// Valid indicates whether the value is a known member of the EventSchemaVersionV2 enum.
func (e EventSchemaVersionV2) Valid() bool {
	switch e {
	case EventSchemaVersionV2N2:
		return true
	default:
		return false
	}
}

// Defines values for EventSchemaVersionV3.
const (
	EventSchemaVersionV3N3 EventSchemaVersionV3 = 3
)

// Valid indicates whether the value is a known member of the EventSchemaVersionV3 enum.
func (e EventSchemaVersionV3) Valid() bool {
	switch e {
	case EventSchemaVersionV3N3:
		return true
	default:
		return false
	}
}

// Defines values for EventSchemaVersionV4.
const (
	EventSchemaVersionV4N4 EventSchemaVersionV4 = 4
)

// Valid indicates whether the value is a known member of the EventSchemaVersionV4 enum.
func (e EventSchemaVersionV4) Valid() bool {
	switch e {
	case EventSchemaVersionV4N4:
		return true
	default:
		return false
	}
}

// Defines values for EventSchemaVersionV5.
const (
	EventSchemaVersionV5N5 EventSchemaVersionV5 = 5
)

// Valid indicates whether the value is a known member of the EventSchemaVersionV5 enum.
func (e EventSchemaVersionV5) Valid() bool {
	switch e {
	case EventSchemaVersionV5N5:
		return true
	default:
		return false
	}
}

// Defines values for StreamAgentSessionEventsV2ParamsEventSchemaVersion.
const (
	StreamAgentSessionEventsV2ParamsEventSchemaVersionN2 StreamAgentSessionEventsV2ParamsEventSchemaVersion = 2
)

// Valid indicates whether the value is a known member of the StreamAgentSessionEventsV2ParamsEventSchemaVersion enum.
func (e StreamAgentSessionEventsV2ParamsEventSchemaVersion) Valid() bool {
	switch e {
	case StreamAgentSessionEventsV2ParamsEventSchemaVersionN2:
		return true
	default:
		return false
	}
}

// Defines values for StreamAgentSessionEventsV3ParamsEventSchemaVersion.
const (
	StreamAgentSessionEventsV3ParamsEventSchemaVersionN3 StreamAgentSessionEventsV3ParamsEventSchemaVersion = 3
)

// Valid indicates whether the value is a known member of the StreamAgentSessionEventsV3ParamsEventSchemaVersion enum.
func (e StreamAgentSessionEventsV3ParamsEventSchemaVersion) Valid() bool {
	switch e {
	case StreamAgentSessionEventsV3ParamsEventSchemaVersionN3:
		return true
	default:
		return false
	}
}

// Defines values for StreamAgentSessionEventsV4ParamsEventSchemaVersion.
const (
	StreamAgentSessionEventsV4ParamsEventSchemaVersionN4 StreamAgentSessionEventsV4ParamsEventSchemaVersion = 4
)

// Valid indicates whether the value is a known member of the StreamAgentSessionEventsV4ParamsEventSchemaVersion enum.
func (e StreamAgentSessionEventsV4ParamsEventSchemaVersion) Valid() bool {
	switch e {
	case StreamAgentSessionEventsV4ParamsEventSchemaVersionN4:
		return true
	default:
		return false
	}
}

// Defines values for StreamAgentSessionEventsV5ParamsEventSchemaVersion.
const (
	StreamAgentSessionEventsV5ParamsEventSchemaVersionN5 StreamAgentSessionEventsV5ParamsEventSchemaVersion = 5
)

// Valid indicates whether the value is a known member of the StreamAgentSessionEventsV5ParamsEventSchemaVersion enum.
func (e StreamAgentSessionEventsV5ParamsEventSchemaVersion) Valid() bool {
	switch e {
	case StreamAgentSessionEventsV5ParamsEventSchemaVersionN5:
		return true
	default:
		return false
	}
}

// AgentHostStatus defines model for AgentHostStatus.
type AgentHostStatus struct {
	Environment string                     `json:"environment"`
	Runtime     RuntimeStatus              `json:"runtime"`
	RuntimeMode AgentHostStatusRuntimeMode `json:"runtime_mode"`
	Service     AgentHostStatusService     `json:"service"`
	Status      AgentHostStatusStatus      `json:"status"`
}

// AgentHostStatusRuntimeMode defines model for AgentHostStatus.RuntimeMode.
type AgentHostStatusRuntimeMode string

// AgentHostStatusService defines model for AgentHostStatus.Service.
type AgentHostStatusService string

// AgentHostStatusStatus defines model for AgentHostStatus.Status.
type AgentHostStatusStatus string

// AgentSession defines model for AgentSession.
type AgentSession struct {
	// ActiveTurnId A UUID when bound, otherwise the empty string.
	ActiveTurnId   UuidOrEmpty        `json:"active_turn_id"`
	AgentSessionId openapi_types.UUID `json:"agent_session_id"`

	// CodexThreadId A UUID when bound, otherwise the empty string.
	CodexThreadId UuidOrEmpty `json:"codex_thread_id"`
	CreatedAt     time.Time   `json:"created_at"`

	// Cwd Rehydrated canonical absolute session working directory.
	Cwd           string                    `json:"cwd"`
	FailureCode   AgentSessionFailureCode   `json:"failure_code"`
	Model         AgentSessionModel         `json:"model"`
	ModelProvider AgentSessionModelProvider `json:"model_provider"`
	State         AgentSessionState         `json:"state"`
	TaskId        openapi_types.UUID        `json:"task_id"`
	UpdatedAt     time.Time                 `json:"updated_at"`
}

// AgentSessionFailureCode defines model for AgentSession.FailureCode.
type AgentSessionFailureCode string

// AgentSessionModel defines model for AgentSession.Model.
type AgentSessionModel string

// AgentSessionModelProvider defines model for AgentSession.ModelProvider.
type AgentSessionModelProvider string

// AgentSessionState defines model for AgentSession.State.
type AgentSessionState string

// ArtifactAcknowledgementV3Request defines model for ArtifactAcknowledgementV3Request.
type ArtifactAcknowledgementV3Request struct {
	// AckId Desktop-selected idempotency identifier scoped to this artifact.
	AckId openapi_types.UUID `json:"ack_id"`

	// LocalCommittedAt UTC timestamp recorded only after Desktop's atomic durable commit succeeds.
	LocalCommittedAt time.Time `json:"local_committed_at"`

	// Sha256 Lowercase SHA-256 verified against the completed event before local commit.
	Sha256 string `json:"sha256"`

	// SizeBytes Exact byte length verified at Desktop's atomic local commit boundary.
	SizeBytes int64 `json:"size_bytes"`
}

// ArtifactAcknowledgementV3Response defines model for ArtifactAcknowledgementV3Response.
type ArtifactAcknowledgementV3Response struct {
	AckId          openapi_types.UUID                             `json:"ack_id"`
	AcknowledgedAt time.Time                                      `json:"acknowledged_at"`
	ArtifactId     openapi_types.UUID                             `json:"artifact_id"`
	CleanupStatus  ArtifactAcknowledgementV3ResponseCleanupStatus `json:"cleanup_status"`
	Status         ArtifactAcknowledgementV3ResponseStatus        `json:"status"`
}

// ArtifactAcknowledgementV3ResponseCleanupStatus defines model for ArtifactAcknowledgementV3Response.CleanupStatus.
type ArtifactAcknowledgementV3ResponseCleanupStatus string

// ArtifactAcknowledgementV3ResponseStatus defines model for ArtifactAcknowledgementV3Response.Status.
type ArtifactAcknowledgementV3ResponseStatus string

// ArtifactErrorResponseV3 Content-free v3 artifact failure. It never contains a path, URL, token, digest, provider payload, or artifact bytes.
type ArtifactErrorResponseV3 struct {
	Error struct {
		Code    ArtifactErrorResponseV3ErrorCode `json:"code"`
		Message string                           `json:"message"`
	} `json:"error"`
}

// ArtifactErrorResponseV3ErrorCode defines model for ArtifactErrorResponseV3.Error.Code.
type ArtifactErrorResponseV3ErrorCode string

// CleanupAgentSessionV2CompletedResponse defines model for CleanupAgentSessionV2CompletedResponse.
type CleanupAgentSessionV2CompletedResponse struct {
	OperationId openapi_types.UUID                            `json:"operation_id"`
	Outcome     CleanupAgentSessionV2CompletedResponseOutcome `json:"outcome"`
	Surfaces    CleanupCompletedSurfaces                      `json:"surfaces"`
}

// CleanupAgentSessionV2CompletedResponseOutcome defines model for CleanupAgentSessionV2CompletedResponse.Outcome.
type CleanupAgentSessionV2CompletedResponseOutcome string

// CleanupAgentSessionV2IncompleteResponse defines model for CleanupAgentSessionV2IncompleteResponse.
type CleanupAgentSessionV2IncompleteResponse struct {
	Error       CleanupIncompleteError                         `json:"error"`
	OperationId openapi_types.UUID                             `json:"operation_id"`
	Outcome     CleanupAgentSessionV2IncompleteResponseOutcome `json:"outcome"`
	Surfaces    CleanupIncompleteSurfaces                      `json:"surfaces"`
}

// CleanupAgentSessionV2IncompleteResponseOutcome defines model for CleanupAgentSessionV2IncompleteResponse.Outcome.
type CleanupAgentSessionV2IncompleteResponseOutcome string

// CleanupAgentSessionV2Request defines model for CleanupAgentSessionV2Request.
type CleanupAgentSessionV2Request struct {
	// OperationId Idempotent deletion-saga operation identifier selected by Desktop.
	OperationId openapi_types.UUID `json:"operation_id"`

	// RequestId Correlation only; never authorization input.
	RequestId *string `json:"request_id,omitempty"`

	// TraceId Correlation only; never authorization input.
	TraceId *string `json:"trace_id,omitempty"`
}

// CleanupCompletedSurfaces defines model for CleanupCompletedSurfaces.
type CleanupCompletedSurfaces struct {
	HostMapping       CleanupCompletedSurfacesHostMapping       `json:"host_mapping"`
	HostReplay        CleanupCompletedSurfacesHostReplay        `json:"host_replay"`
	RuntimeThreadTree CleanupCompletedSurfacesRuntimeThreadTree `json:"runtime_thread_tree"`
}

// CleanupCompletedSurfacesHostMapping defines model for CleanupCompletedSurfaces.HostMapping.
type CleanupCompletedSurfacesHostMapping string

// CleanupCompletedSurfacesHostReplay defines model for CleanupCompletedSurfaces.HostReplay.
type CleanupCompletedSurfacesHostReplay string

// CleanupCompletedSurfacesRuntimeThreadTree defines model for CleanupCompletedSurfaces.RuntimeThreadTree.
type CleanupCompletedSurfacesRuntimeThreadTree string

// CleanupIncompleteError defines model for CleanupIncompleteError.
type CleanupIncompleteError struct {
	Code       CleanupIncompleteErrorCode       `json:"code"`
	Message    string                           `json:"message"`
	ReasonCode CleanupIncompleteErrorReasonCode `json:"reason_code"`
}

// CleanupIncompleteErrorCode defines model for CleanupIncompleteError.Code.
type CleanupIncompleteErrorCode string

// CleanupIncompleteErrorReasonCode defines model for CleanupIncompleteError.ReasonCode.
type CleanupIncompleteErrorReasonCode string

// CleanupIncompleteSurfaces defines model for CleanupIncompleteSurfaces.
type CleanupIncompleteSurfaces struct {
	HostMapping       CleanupSurfaceStatus `json:"host_mapping"`
	HostReplay        CleanupSurfaceStatus `json:"host_replay"`
	RuntimeThreadTree CleanupSurfaceStatus `json:"runtime_thread_tree"`
}

// CleanupOperationConflictError defines model for CleanupOperationConflictError.
type CleanupOperationConflictError struct {
	Error struct {
		Code    CleanupOperationConflictErrorErrorCode `json:"code"`
		Message string                                 `json:"message"`
	} `json:"error"`
}

// CleanupOperationConflictErrorErrorCode defines model for CleanupOperationConflictError.Error.Code.
type CleanupOperationConflictErrorErrorCode string

// CleanupSurfaceStatus defines model for CleanupSurfaceStatus.
type CleanupSurfaceStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// GenerateTitleV2Request defines model for GenerateTitleV2Request.
type GenerateTitleV2Request struct {
	// Input First user text only; non-blank and at most 8 KiB UTF-8.
	Input string `json:"input"`

	// OperationId Idempotent title-generation operation identifier selected by Desktop.
	OperationId openapi_types.UUID `json:"operation_id"`

	// RequestId Correlation only; never authorization input.
	RequestId *string `json:"request_id,omitempty"`

	// TraceId Correlation only; never authorization input.
	TraceId *string `json:"trace_id,omitempty"`
}

// GenerateTitleV2Response defines model for GenerateTitleV2Response.
type GenerateTitleV2Response struct {
	OperationId openapi_types.UUID `json:"operation_id"`

	// Title NFC, one-line untrusted plain text with 1..40 grapheme clusters and no control, bidi-control, HTML, or Markdown syntax.
	Title string `json:"title"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service HealthResponseService `json:"service"`
	Status  HealthResponseStatus  `json:"status"`
}

// HealthResponseService defines model for HealthResponse.Service.
type HealthResponseService string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ManagedSkill defines model for ManagedSkill.
type ManagedSkill struct {
	CapabilityReadiness ManagedSkillCapabilityReadiness `json:"capability_readiness"`

	// CatalogBlockedReason Required by the Skills v1 semantic contract for every blocked catalog
	// projection and omitted for an installable entry. It exposes exactly
	// one stable primary reason and never includes source text, archive
	// metadata, filesystem locations, or free-form upstream failure details.
	CatalogBlockedReason *ManagedSkillCatalogBlockedReason `json:"catalog_blocked_reason,omitempty"`
	CatalogStatus        ManagedSkillCatalogStatus         `json:"catalog_status"`

	// Enabled False when not installed or explicitly disabled.
	Enabled            bool                           `json:"enabled"`
	FailureCode        ManagedSkillFailureCode        `json:"failure_code"`
	Id                 SkillIdValue                   `json:"id"`
	InstallationStatus ManagedSkillInstallationStatus `json:"installation_status"`
	MaintenanceStatus  ManagedSkillMaintenanceStatus  `json:"maintenance_status"`
	RuntimeName        string                         `json:"runtime_name"`

	// RuntimeVisible True only after Runtime confirms the exact installed and enabled Skill in its current projection.
	RuntimeVisible bool            `json:"runtime_visible"`
	Version        SemanticVersion `json:"version"`
}

// ManagedSkillCapabilityReadiness defines model for ManagedSkill.CapabilityReadiness.
type ManagedSkillCapabilityReadiness string

// ManagedSkillCatalogBlockedReason Required by the Skills v1 semantic contract for every blocked catalog
// projection and omitted for an installable entry. It exposes exactly
// one stable primary reason and never includes source text, archive
// metadata, filesystem locations, or free-form upstream failure details.
type ManagedSkillCatalogBlockedReason string

// ManagedSkillCatalogStatus defines model for ManagedSkill.CatalogStatus.
type ManagedSkillCatalogStatus string

// ManagedSkillFailureCode defines model for ManagedSkill.FailureCode.
type ManagedSkillFailureCode string

// ManagedSkillInstallationStatus defines model for ManagedSkill.InstallationStatus.
type ManagedSkillInstallationStatus string

// ManagedSkillMaintenanceStatus defines model for ManagedSkill.MaintenanceStatus.
type ManagedSkillMaintenanceStatus string

// NotReadyResponse defines model for NotReadyResponse.
type NotReadyResponse struct {
	RuntimeState RuntimeState           `json:"runtime_state"`
	Status       NotReadyResponseStatus `json:"status"`
}

// NotReadyResponseStatus defines model for NotReadyResponse.Status.
type NotReadyResponseStatus string

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	RuntimeState ReadyResponseRuntimeState `json:"runtime_state"`
	Status       ReadyResponseStatus       `json:"status"`
}

// ReadyResponseRuntimeState defines model for ReadyResponse.RuntimeState.
type ReadyResponseRuntimeState string

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// RuntimeState defines model for RuntimeState.
type RuntimeState string

// RuntimeStatus defines model for RuntimeStatus.
type RuntimeStatus struct {
	ExperimentalApi RuntimeStatusExperimentalApi `json:"experimental_api"`
	FailureCode     *RuntimeStatusFailureCode    `json:"failure_code,omitempty"`
	Model           *RuntimeStatusModel          `json:"model,omitempty"`
	ModelProvider   *RuntimeStatusModelProvider  `json:"model_provider,omitempty"`
	Ready           bool                         `json:"ready"`
	RuntimeVersion  *RuntimeStatusRuntimeVersion `json:"runtime_version,omitempty"`
	State           RuntimeState                 `json:"state"`
	Transport       RuntimeStatusTransport       `json:"transport"`
	UpstreamCommit  *RuntimeStatusUpstreamCommit `json:"upstream_commit,omitempty"`
	UpstreamTag     *RuntimeStatusUpstreamTag    `json:"upstream_tag,omitempty"`
}

// RuntimeStatusExperimentalApi defines model for RuntimeStatus.ExperimentalApi.
type RuntimeStatusExperimentalApi bool

// RuntimeStatusFailureCode defines model for RuntimeStatus.FailureCode.
type RuntimeStatusFailureCode string

// RuntimeStatusModel defines model for RuntimeStatus.Model.
type RuntimeStatusModel string

// RuntimeStatusModelProvider defines model for RuntimeStatus.ModelProvider.
type RuntimeStatusModelProvider string

// RuntimeStatusRuntimeVersion defines model for RuntimeStatus.RuntimeVersion.
type RuntimeStatusRuntimeVersion string

// RuntimeStatusTransport defines model for RuntimeStatus.Transport.
type RuntimeStatusTransport string

// RuntimeStatusUpstreamCommit defines model for RuntimeStatus.UpstreamCommit.
type RuntimeStatusUpstreamCommit string

// RuntimeStatusUpstreamTag defines model for RuntimeStatus.UpstreamTag.
type RuntimeStatusUpstreamTag string

// SemanticVersion defines model for SemanticVersion.
type SemanticVersion = string

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	Session AgentSession `json:"session"`
}

// Sha256 Lowercase SHA-256. When this schema is used by a property named `catalog_revision`, the digest is over the exact raw validated `bundle-manifest.json` bytes; install compares it in constant time without re-serialization or normalization.
type Sha256 = string

// SkillEnabledRequest defines model for SkillEnabledRequest.
type SkillEnabledRequest struct {
	Enabled     bool               `json:"enabled"`
	OperationId openapi_types.UUID `json:"operation_id"`
}

// SkillErrorResponse Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillErrorResponse struct {
	Error struct {
		Code    SkillErrorResponseErrorCode `json:"code"`
		Message string                      `json:"message"`
	} `json:"error"`
}

// SkillErrorResponseErrorCode defines model for SkillErrorResponse.Error.Code.
type SkillErrorResponseErrorCode string

// SkillIdValue defines model for SkillIdValue.
type SkillIdValue = string

// SkillInstallRequest defines model for SkillInstallRequest.
type SkillInstallRequest struct {
	// CatalogRevision Lowercase SHA-256. When this schema is used by a property named `catalog_revision`, the digest is over the exact raw validated `bundle-manifest.json` bytes; install compares it in constant time without re-serialization or normalization.
	CatalogRevision Sha256 `json:"catalog_revision"`

	// ExpectedArchiveSha256 Lowercase SHA-256. When this schema is used by a property named `catalog_revision`, the digest is over the exact raw validated `bundle-manifest.json` bytes; install compares it in constant time without re-serialization or normalization.
	ExpectedArchiveSha256 Sha256             `json:"expected_archive_sha256"`
	ExpectedVersion       SemanticVersion    `json:"expected_version"`
	OperationId           openapi_types.UUID `json:"operation_id"`
}

// SkillListResponse defines model for SkillListResponse.
type SkillListResponse struct {
	// CatalogRevision Lowercase SHA-256. When this schema is used by a property named `catalog_revision`, the digest is over the exact raw validated `bundle-manifest.json` bytes; install compares it in constant time without re-serialization or normalization.
	CatalogRevision Sha256                         `json:"catalog_revision"`
	ScannedAt       time.Time                      `json:"scanned_at"`
	SchemaVersion   SkillListResponseSchemaVersion `json:"schema_version"`
	Skills          []ManagedSkill                 `json:"skills"`
}

// SkillListResponseSchemaVersion defines model for SkillListResponse.SchemaVersion.
type SkillListResponseSchemaVersion int32

// SkillMutationResponse defines model for SkillMutationResponse.
type SkillMutationResponse struct {
	OperationId openapi_types.UUID           `json:"operation_id"`
	Outcome     SkillMutationResponseOutcome `json:"outcome"`
	Skill       ManagedSkill                 `json:"skill"`
}

// SkillMutationResponseOutcome defines model for SkillMutationResponse.Outcome.
type SkillMutationResponseOutcome string

// SkillScanRequest defines model for SkillScanRequest.
type SkillScanRequest struct {
	OperationId openapi_types.UUID     `json:"operation_id"`
	Reason      SkillScanRequestReason `json:"reason"`
}

// SkillScanRequestReason defines model for SkillScanRequest.Reason.
type SkillScanRequestReason string

// SkillScanResponse defines model for SkillScanResponse.
type SkillScanResponse struct {
	// CatalogRevision Lowercase SHA-256. When this schema is used by a property named `catalog_revision`, the digest is over the exact raw validated `bundle-manifest.json` bytes; install compares it in constant time without re-serialization or normalization.
	CatalogRevision Sha256                   `json:"catalog_revision"`
	OperationId     openapi_types.UUID       `json:"operation_id"`
	Outcome         SkillScanResponseOutcome `json:"outcome"`
	ScannedAt       time.Time                `json:"scanned_at"`
	Skills          []ManagedSkill           `json:"skills"`
}

// SkillScanResponseOutcome defines model for SkillScanResponse.Outcome.
type SkillScanResponseOutcome string

// SkillUninstallRequest defines model for SkillUninstallRequest.
type SkillUninstallRequest struct {
	OperationId openapi_types.UUID `json:"operation_id"`
}

// StartSessionRequest defines model for StartSessionRequest.
type StartSessionRequest struct {
	// Cwd Existing absolute local directory. Host resolves symlinks and uses the
	// resulting canonical path as the session working directory. Any private
	// persistence representation is an implementation detail and is not part
	// of this wire contract.
	Cwd string `json:"cwd"`

	// RequestId Optional request correlation identifier copied to session events.
	RequestId *string `json:"request_id,omitempty"`

	// TenantId Optional correlation context only; it does not grant tenant access.
	TenantId *string `json:"tenant_id,omitempty"`

	// TraceId Optional correlation identifier copied to session events.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId Optional correlation context only; it does not authenticate a user.
	UserId *string `json:"user_id,omitempty"`
}

// StartTurnRequest defines model for StartTurnRequest.
type StartTurnRequest struct {
	// Input Text-only turn input. It must contain a non-whitespace character and
	// must not exceed 1 MiB in UTF-8 bytes. The complete JSON body is also
	// capped at 1 MiB.
	Input string `json:"input"`

	// ReasoningEffort Omit or send the empty string for `none`; clients should prefer omission, `none`, or `high`.
	ReasoningEffort *StartTurnRequestReasoningEffort `json:"reasoning_effort,omitempty"`

	// RequestId Optional request correlation identifier copied to events from this operation onward.
	RequestId *string `json:"request_id,omitempty"`

	// TenantId Optional correlation context only; it does not grant tenant access.
	TenantId *string `json:"tenant_id,omitempty"`

	// TraceId Optional correlation identifier copied to events from this operation onward.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId Optional correlation context only; it does not authenticate a user.
	UserId *string `json:"user_id,omitempty"`
}

// StartTurnRequestReasoningEffort Omit or send the empty string for `none`; clients should prefer omission, `none`, or `high`.
type StartTurnRequestReasoningEffort string

// StartTurnResponse defines model for StartTurnResponse.
type StartTurnResponse struct {
	TurnId openapi_types.UUID `json:"turn_id"`
}

// StartTurnV2ContentBlock A closed content-block union discriminated by `type`.
type StartTurnV2ContentBlock struct {
	union json.RawMessage
}

// StartTurnV2FileBlock defines model for StartTurnV2FileBlock.
type StartTurnV2FileBlock struct {
	// AttachmentId Desktop attachment identifier; correlation only, never a local path.
	AttachmentId openapi_types.UUID `json:"attachment_id"`

	// ContextChunks Ordered, untrusted plain-text excerpts selected locally from this file.
	// Host maps them to bounded Runtime text input and never persists them.
	// UTF-8 bytes across every file block in the turn must be at most 256 KiB.
	ContextChunks []string `json:"context_chunks"`

	// MediaType Canonical media type produced after Desktop format and container validation.
	MediaType StartTurnV2FileMediaType `json:"media_type"`

	// Name NFC display basename with no path separator, control character, or
	// leading/trailing whitespace. It is untrusted text and must never be
	// interpreted as a path, markup, authorization input, or log label.
	Name string `json:"name"`

	// Sha256 Lowercase hexadecimal SHA-256 of the original file bytes, verified by Desktop.
	Sha256 string `json:"sha256"`

	// SizeBytes Exact original file byte length verified by Desktop before parsing.
	SizeBytes int64                    `json:"size_bytes"`
	Type      StartTurnV2FileBlockType `json:"type"`
}

// StartTurnV2FileBlockType defines model for StartTurnV2FileBlock.Type.
type StartTurnV2FileBlockType string

// StartTurnV2FileMediaType Canonical media type produced after Desktop format and container validation.
type StartTurnV2FileMediaType string

// StartTurnV2ImageBlock defines model for StartTurnV2ImageBlock.
type StartTurnV2ImageBlock struct {
	// AttachmentId Desktop attachment identifier; correlation only, never a local path.
	AttachmentId openapi_types.UUID `json:"attachment_id"`

	// DataUrl Canonical base64 data URL. Its header must equal `media_type`; decoded
	// length must equal `size_bytes`; and decoded SHA-256 must equal `sha256`.
	// Host validates all three relationships before invoking Runtime and
	// never persists this value.
	DataUrl   string                         `json:"data_url"`
	MediaType StartTurnV2ImageBlockMediaType `json:"media_type"`

	// Sha256 Lowercase hexadecimal SHA-256 of the decoded image bytes.
	Sha256 string `json:"sha256"`

	// SizeBytes Exact decoded image byte length.
	SizeBytes int64                     `json:"size_bytes"`
	Type      StartTurnV2ImageBlockType `json:"type"`
}

// StartTurnV2ImageBlockMediaType defines model for StartTurnV2ImageBlock.MediaType.
type StartTurnV2ImageBlockMediaType string

// StartTurnV2ImageBlockType defines model for StartTurnV2ImageBlock.Type.
type StartTurnV2ImageBlockType string

// StartTurnV2Request defines model for StartTurnV2Request.
type StartTurnV2Request struct {
	// ContentBlocks Ordered Runtime input. Array order is message order and must be
	// preserved when Host maps blocks to Runtime UserInput values. The
	// request may contain at most 10 image/file blocks. Decoded image bytes
	// across all image blocks must be at most 10 MiB; UTF-8 bytes across all
	// file `context_chunks` must be at most 256 KiB. Those aggregate limits
	// are validated semantically before Runtime invocation.
	ContentBlocks []StartTurnV2ContentBlock `json:"content_blocks"`

	// OperationId Desktop-selected idempotency identifier scoped to this Agent session.
	// The same canonical ordered input returns the original accepted turn;
	// reuse with different input returns `turn_operation_conflict`.
	OperationId openapi_types.UUID `json:"operation_id"`

	// ReasoningEffort Omit or send the empty string for `none`; clients should prefer omission, `none`, or `high`.
	ReasoningEffort *StartTurnV2RequestReasoningEffort `json:"reasoning_effort,omitempty"`

	// RequestId Optional request correlation identifier copied to events from this operation onward.
	RequestId *string `json:"request_id,omitempty"`

	// TenantId Optional correlation context only; it does not grant tenant access.
	TenantId *string `json:"tenant_id,omitempty"`

	// TraceId Optional correlation identifier copied to events from this operation onward.
	TraceId *string `json:"trace_id,omitempty"`

	// UserId Optional correlation context only; it does not authenticate a user.
	UserId *string `json:"user_id,omitempty"`
}

// StartTurnV2RequestReasoningEffort Omit or send the empty string for `none`; clients should prefer omission, `none`, or `high`.
type StartTurnV2RequestReasoningEffort string

// StartTurnV2TextBlock defines model for StartTurnV2TextBlock.
type StartTurnV2TextBlock struct {
	// Text Non-blank user text, bounded to 1 MiB in UTF-8 bytes.
	Text string                   `json:"text"`
	Type StartTurnV2TextBlockType `json:"type"`
}

// StartTurnV2TextBlockType defines model for StartTurnV2TextBlock.Type.
type StartTurnV2TextBlockType string

// TitleGenerationUnavailableError defines model for TitleGenerationUnavailableError.
type TitleGenerationUnavailableError struct {
	Error struct {
		Code    TitleGenerationUnavailableErrorErrorCode `json:"code"`
		Message string                                   `json:"message"`
	} `json:"error"`
}

// TitleGenerationUnavailableErrorErrorCode defines model for TitleGenerationUnavailableError.Error.Code.
type TitleGenerationUnavailableErrorErrorCode string

// TitleOperationConflictError defines model for TitleOperationConflictError.
type TitleOperationConflictError struct {
	Error struct {
		Code    TitleOperationConflictErrorErrorCode `json:"code"`
		Message string                               `json:"message"`
	} `json:"error"`
}

// TitleOperationConflictErrorErrorCode defines model for TitleOperationConflictError.Error.Code.
type TitleOperationConflictErrorErrorCode string

// TitleOutputInvalidError defines model for TitleOutputInvalidError.
type TitleOutputInvalidError struct {
	Error struct {
		Code    TitleOutputInvalidErrorErrorCode `json:"code"`
		Message string                           `json:"message"`
	} `json:"error"`
}

// TitleOutputInvalidErrorErrorCode defines model for TitleOutputInvalidError.Error.Code.
type TitleOutputInvalidErrorErrorCode string

// TraceRequest Correlation metadata copied to subsequent events. `{}` is valid. These
// values are correlation context, not authentication or authorization input.
type TraceRequest struct {
	RequestId *string `json:"request_id,omitempty"`
	TenantId  *string `json:"tenant_id,omitempty"`
	TraceId   *string `json:"trace_id,omitempty"`
	UserId    *string `json:"user_id,omitempty"`
}

// TurnOperationConflictError defines model for TurnOperationConflictError.
type TurnOperationConflictError struct {
	Error struct {
		Code    TurnOperationConflictErrorErrorCode `json:"code"`
		Message string                              `json:"message"`
	} `json:"error"`
}

// TurnOperationConflictErrorErrorCode defines model for TurnOperationConflictError.Error.Code.
type TurnOperationConflictErrorErrorCode string

// UuidOrEmpty A UUID when bound, otherwise the empty string.
type UuidOrEmpty = string

// AgentSessionId defines model for AgentSessionId.
type AgentSessionId = openapi_types.UUID

// ArtifactId defines model for ArtifactId.
type ArtifactId = openapi_types.UUID

// ByteRange defines model for ByteRange.
type ByteRange = string

// EventAfter defines model for EventAfter.
type EventAfter = uint64

// EventSchemaVersionV2 defines model for EventSchemaVersionV2.
type EventSchemaVersionV2 int32

// EventSchemaVersionV3 defines model for EventSchemaVersionV3.
type EventSchemaVersionV3 int32

// EventSchemaVersionV4 defines model for EventSchemaVersionV4.
type EventSchemaVersionV4 int32

// EventSchemaVersionV5 defines model for EventSchemaVersionV5.
type EventSchemaVersionV5 int32

// EventStreamId defines model for EventStreamId.
type EventStreamId = openapi_types.UUID

// LastEventId defines model for LastEventId.
type LastEventId = string

// SkillId defines model for SkillId.
type SkillId = string

// TaskId defines model for TaskId.
type TaskId = openapi_types.UUID

// TurnId defines model for TurnId.
type TurnId = openapi_types.UUID

// ArtifactBadRequest Content-free v3 artifact failure. It never contains a path, URL, token, digest, provider payload, or artifact bytes.
type ArtifactBadRequest = ArtifactErrorResponseV3

// ArtifactExpired Content-free v3 artifact failure. It never contains a path, URL, token, digest, provider payload, or artifact bytes.
type ArtifactExpired = ArtifactErrorResponseV3

// ArtifactInternalError Content-free v3 artifact failure. It never contains a path, URL, token, digest, provider payload, or artifact bytes.
type ArtifactInternalError = ArtifactErrorResponseV3

// ArtifactNotFound Content-free v3 artifact failure. It never contains a path, URL, token, digest, provider payload, or artifact bytes.
type ArtifactNotFound = ArtifactErrorResponseV3

// ArtifactRangeNotSatisfiable Content-free v3 artifact failure. It never contains a path, URL, token, digest, provider payload, or artifact bytes.
type ArtifactRangeNotSatisfiable = ArtifactErrorResponseV3

// ArtifactUnauthorized Content-free v3 artifact failure. It never contains a path, URL, token, digest, provider payload, or artifact bytes.
type ArtifactUnauthorized = ArtifactErrorResponseV3

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// RuntimeRequestFailed defines model for RuntimeRequestFailed.
type RuntimeRequestFailed = ErrorResponse

// SessionNotFound defines model for SessionNotFound.
type SessionNotFound = ErrorResponse

// SkillBadRequest Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillBadRequest = SkillErrorResponse

// SkillConflict Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillConflict = SkillErrorResponse

// SkillForbidden Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillForbidden = SkillErrorResponse

// SkillInternalError Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillInternalError = SkillErrorResponse

// SkillNotFound Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillNotFound = SkillErrorResponse

// SkillUnauthorized Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillUnauthorized = SkillErrorResponse

// SkillUnavailable Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillUnavailable = SkillErrorResponse

// SkillUnprocessable Content-free Skill management failure. It never contains a path, token, archive bytes, Skill instructions, or Runtime payload.
type SkillUnprocessable = SkillErrorResponse

// TitleGenerationUnavailable defines model for TitleGenerationUnavailable.
type TitleGenerationUnavailable = TitleGenerationUnavailableError

// TitleOperationConflict defines model for TitleOperationConflict.
type TitleOperationConflict = TitleOperationConflictError

// TitleOutputInvalid defines model for TitleOutputInvalid.
type TitleOutputInvalid = TitleOutputInvalidError

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// localBearerContextKey is the context key for localBearer security scheme
type localBearerContextKey string

// StreamAgentSessionEventsParams defines parameters for StreamAgentSessionEvents.
type StreamAgentSessionEventsParams struct {
	// StreamId Expected process-local stream identifier. Required when `after > 0`
	// unless `Last-Event-ID` supplies the complete cursor. A mismatch returns
	// `409 event_stream_changed`.
	StreamId *EventStreamId `form:"stream_id,omitempty" json:"stream_id,omitempty"`

	// After Unsigned 64-bit sequence after which events are replayed. Defaults to
	// zero. Values greater than zero require a matching stream ID. Ignored when
	// `Last-Event-ID` is present.
	After *EventAfter `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID Complete SSE cursor `<stream_id>:<sequence>`. Sequence is a decimal
	// unsigned 64-bit integer from 1 through 18446744073709551615 with no
	// leading zero. The header overrides `stream_id` and `after` query parameters.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// CleanupAgentSessionV2409JSONResponseBody defines parameters for CleanupAgentSessionV2.
type CleanupAgentSessionV2409JSONResponseBody struct {
	union json.RawMessage
}

// StreamAgentSessionEventsV2Params defines parameters for StreamAgentSessionEventsV2.
type StreamAgentSessionEventsV2Params struct {
	// EventSchemaVersion Explicit negotiation guard. Only integer value 2 is accepted on the v2 event stream.
	EventSchemaVersion StreamAgentSessionEventsV2ParamsEventSchemaVersion `form:"event_schema_version" json:"event_schema_version"`

	// StreamId Expected process-local stream identifier. Required when `after > 0`
	// unless `Last-Event-ID` supplies the complete cursor. A mismatch returns
	// `409 event_stream_changed`.
	StreamId *EventStreamId `form:"stream_id,omitempty" json:"stream_id,omitempty"`

	// After Unsigned 64-bit sequence after which events are replayed. Defaults to
	// zero. Values greater than zero require a matching stream ID. Ignored when
	// `Last-Event-ID` is present.
	After *EventAfter `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID Complete SSE cursor `<stream_id>:<sequence>`. Sequence is a decimal
	// unsigned 64-bit integer from 1 through 18446744073709551615 with no
	// leading zero. The header overrides `stream_id` and `after` query parameters.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// StreamAgentSessionEventsV2ParamsEventSchemaVersion defines parameters for StreamAgentSessionEventsV2.
type StreamAgentSessionEventsV2ParamsEventSchemaVersion int32

// StartAgentTurnV2409JSONResponseBody defines parameters for StartAgentTurnV2.
type StartAgentTurnV2409JSONResponseBody struct {
	union json.RawMessage
}

// GetAgentArtifactContentV3Params defines parameters for GetAgentArtifactContentV3.
type GetAgentArtifactContentV3Params struct {
	// Range A single inclusive HTTP byte range. Multiple or malformed ranges are rejected.
	Range *ByteRange `json:"Range,omitempty"`
}

// GetAgentArtifactPosterV3Params defines parameters for GetAgentArtifactPosterV3.
type GetAgentArtifactPosterV3Params struct {
	// Range A single inclusive HTTP byte range. Multiple or malformed ranges are rejected.
	Range *ByteRange `json:"Range,omitempty"`
}

// StreamAgentSessionEventsV3Params defines parameters for StreamAgentSessionEventsV3.
type StreamAgentSessionEventsV3Params struct {
	// EventSchemaVersion Explicit negotiation guard. Only integer value 3 is accepted on the v3 event stream.
	EventSchemaVersion StreamAgentSessionEventsV3ParamsEventSchemaVersion `form:"event_schema_version" json:"event_schema_version"`

	// StreamId Expected process-local stream identifier. Required when `after > 0`
	// unless `Last-Event-ID` supplies the complete cursor. A mismatch returns
	// `409 event_stream_changed`.
	StreamId *EventStreamId `form:"stream_id,omitempty" json:"stream_id,omitempty"`

	// After Unsigned 64-bit sequence after which events are replayed. Defaults to
	// zero. Values greater than zero require a matching stream ID. Ignored when
	// `Last-Event-ID` is present.
	After *EventAfter `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID Complete SSE cursor `<stream_id>:<sequence>`. Sequence is a decimal
	// unsigned 64-bit integer from 1 through 18446744073709551615 with no
	// leading zero. The header overrides `stream_id` and `after` query parameters.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// StreamAgentSessionEventsV3ParamsEventSchemaVersion defines parameters for StreamAgentSessionEventsV3.
type StreamAgentSessionEventsV3ParamsEventSchemaVersion int32

// StreamAgentSessionEventsV4Params defines parameters for StreamAgentSessionEventsV4.
type StreamAgentSessionEventsV4Params struct {
	// EventSchemaVersion Explicit negotiation guard. Only integer value 4 is accepted on the v4 event stream.
	EventSchemaVersion StreamAgentSessionEventsV4ParamsEventSchemaVersion `form:"event_schema_version" json:"event_schema_version"`

	// StreamId Expected process-local stream identifier. Required when `after > 0`
	// unless `Last-Event-ID` supplies the complete cursor. A mismatch returns
	// `409 event_stream_changed`.
	StreamId *EventStreamId `form:"stream_id,omitempty" json:"stream_id,omitempty"`

	// After Unsigned 64-bit sequence after which events are replayed. Defaults to
	// zero. Values greater than zero require a matching stream ID. Ignored when
	// `Last-Event-ID` is present.
	After *EventAfter `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID Complete SSE cursor `<stream_id>:<sequence>`. Sequence is a decimal
	// unsigned 64-bit integer from 1 through 18446744073709551615 with no
	// leading zero. The header overrides `stream_id` and `after` query parameters.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// StreamAgentSessionEventsV4ParamsEventSchemaVersion defines parameters for StreamAgentSessionEventsV4.
type StreamAgentSessionEventsV4ParamsEventSchemaVersion int32

// StreamAgentSessionEventsV5Params defines parameters for StreamAgentSessionEventsV5.
type StreamAgentSessionEventsV5Params struct {
	// EventSchemaVersion Explicit negotiation guard. Only integer value 5 is accepted on the v5 event stream.
	EventSchemaVersion StreamAgentSessionEventsV5ParamsEventSchemaVersion `form:"event_schema_version" json:"event_schema_version"`

	// StreamId Expected process-local stream identifier. Required when `after > 0`
	// unless `Last-Event-ID` supplies the complete cursor. A mismatch returns
	// `409 event_stream_changed`.
	StreamId *EventStreamId `form:"stream_id,omitempty" json:"stream_id,omitempty"`

	// After Unsigned 64-bit sequence after which events are replayed. Defaults to
	// zero. Values greater than zero require a matching stream ID. Ignored when
	// `Last-Event-ID` is present.
	After *EventAfter `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID Complete SSE cursor `<stream_id>:<sequence>`. Sequence is a decimal
	// unsigned 64-bit integer from 1 through 18446744073709551615 with no
	// leading zero. The header overrides `stream_id` and `after` query parameters.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// StreamAgentSessionEventsV5ParamsEventSchemaVersion defines parameters for StreamAgentSessionEventsV5.
type StreamAgentSessionEventsV5ParamsEventSchemaVersion int32

// ResumeAgentSessionJSONRequestBody defines body for ResumeAgentSession for application/json ContentType.
type ResumeAgentSessionJSONRequestBody = TraceRequest

// StartAgentTurnJSONRequestBody defines body for StartAgentTurn for application/json ContentType.
type StartAgentTurnJSONRequestBody = StartTurnRequest

// InterruptAgentTurnJSONRequestBody defines body for InterruptAgentTurn for application/json ContentType.
type InterruptAgentTurnJSONRequestBody = TraceRequest

// ScanManagedSkillsJSONRequestBody defines body for ScanManagedSkills for application/json ContentType.
type ScanManagedSkillsJSONRequestBody = SkillScanRequest

// SetManagedSkillEnabledJSONRequestBody defines body for SetManagedSkillEnabled for application/json ContentType.
type SetManagedSkillEnabledJSONRequestBody = SkillEnabledRequest

// InstallManagedSkillJSONRequestBody defines body for InstallManagedSkill for application/json ContentType.
type InstallManagedSkillJSONRequestBody = SkillInstallRequest

// UninstallManagedSkillJSONRequestBody defines body for UninstallManagedSkill for application/json ContentType.
type UninstallManagedSkillJSONRequestBody = SkillUninstallRequest

// StartAgentSessionJSONRequestBody defines body for StartAgentSession for application/json ContentType.
type StartAgentSessionJSONRequestBody = StartSessionRequest

// CleanupAgentSessionV2JSONRequestBody defines body for CleanupAgentSessionV2 for application/json ContentType.
type CleanupAgentSessionV2JSONRequestBody = CleanupAgentSessionV2Request

// GenerateAgentSessionTitleV2JSONRequestBody defines body for GenerateAgentSessionTitleV2 for application/json ContentType.
type GenerateAgentSessionTitleV2JSONRequestBody = GenerateTitleV2Request

// StartAgentTurnV2JSONRequestBody defines body for StartAgentTurnV2 for application/json ContentType.
type StartAgentTurnV2JSONRequestBody = StartTurnV2Request

// AcknowledgeAgentArtifactV3JSONRequestBody defines body for AcknowledgeAgentArtifactV3 for application/json ContentType.
type AcknowledgeAgentArtifactV3JSONRequestBody = ArtifactAcknowledgementV3Request

// AsStartTurnV2TextBlock returns the union data inside the StartTurnV2ContentBlock as a StartTurnV2TextBlock
func (t StartTurnV2ContentBlock) AsStartTurnV2TextBlock() (StartTurnV2TextBlock, error) {
	var body StartTurnV2TextBlock
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartTurnV2TextBlock overwrites any union data inside the StartTurnV2ContentBlock as the provided StartTurnV2TextBlock
func (t *StartTurnV2ContentBlock) FromStartTurnV2TextBlock(v StartTurnV2TextBlock) error {
	v.Type = "text"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartTurnV2TextBlock performs a merge with any union data inside the StartTurnV2ContentBlock, using the provided StartTurnV2TextBlock
func (t *StartTurnV2ContentBlock) MergeStartTurnV2TextBlock(v StartTurnV2TextBlock) error {
	v.Type = "text"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStartTurnV2ImageBlock returns the union data inside the StartTurnV2ContentBlock as a StartTurnV2ImageBlock
func (t StartTurnV2ContentBlock) AsStartTurnV2ImageBlock() (StartTurnV2ImageBlock, error) {
	var body StartTurnV2ImageBlock
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartTurnV2ImageBlock overwrites any union data inside the StartTurnV2ContentBlock as the provided StartTurnV2ImageBlock
func (t *StartTurnV2ContentBlock) FromStartTurnV2ImageBlock(v StartTurnV2ImageBlock) error {
	v.Type = "image"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartTurnV2ImageBlock performs a merge with any union data inside the StartTurnV2ContentBlock, using the provided StartTurnV2ImageBlock
func (t *StartTurnV2ContentBlock) MergeStartTurnV2ImageBlock(v StartTurnV2ImageBlock) error {
	v.Type = "image"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStartTurnV2FileBlock returns the union data inside the StartTurnV2ContentBlock as a StartTurnV2FileBlock
func (t StartTurnV2ContentBlock) AsStartTurnV2FileBlock() (StartTurnV2FileBlock, error) {
	var body StartTurnV2FileBlock
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartTurnV2FileBlock overwrites any union data inside the StartTurnV2ContentBlock as the provided StartTurnV2FileBlock
func (t *StartTurnV2ContentBlock) FromStartTurnV2FileBlock(v StartTurnV2FileBlock) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartTurnV2FileBlock performs a merge with any union data inside the StartTurnV2ContentBlock, using the provided StartTurnV2FileBlock
func (t *StartTurnV2ContentBlock) MergeStartTurnV2FileBlock(v StartTurnV2FileBlock) error {
	v.Type = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StartTurnV2ContentBlock) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t StartTurnV2ContentBlock) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsStartTurnV2FileBlock()
	case "image":
		return t.AsStartTurnV2ImageBlock()
	case "text":
		return t.AsStartTurnV2TextBlock()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t StartTurnV2ContentBlock) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StartTurnV2ContentBlock) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCleanupAgentSessionV2IncompleteResponse returns the union data inside the CleanupAgentSessionV2409JSONResponseBody as a CleanupAgentSessionV2IncompleteResponse
func (t CleanupAgentSessionV2409JSONResponseBody) AsCleanupAgentSessionV2IncompleteResponse() (CleanupAgentSessionV2IncompleteResponse, error) {
	var body CleanupAgentSessionV2IncompleteResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanupAgentSessionV2IncompleteResponse overwrites any union data inside the CleanupAgentSessionV2409JSONResponseBody as the provided CleanupAgentSessionV2IncompleteResponse
func (t *CleanupAgentSessionV2409JSONResponseBody) FromCleanupAgentSessionV2IncompleteResponse(v CleanupAgentSessionV2IncompleteResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanupAgentSessionV2IncompleteResponse performs a merge with any union data inside the CleanupAgentSessionV2409JSONResponseBody, using the provided CleanupAgentSessionV2IncompleteResponse
func (t *CleanupAgentSessionV2409JSONResponseBody) MergeCleanupAgentSessionV2IncompleteResponse(v CleanupAgentSessionV2IncompleteResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleanupOperationConflictError returns the union data inside the CleanupAgentSessionV2409JSONResponseBody as a CleanupOperationConflictError
func (t CleanupAgentSessionV2409JSONResponseBody) AsCleanupOperationConflictError() (CleanupOperationConflictError, error) {
	var body CleanupOperationConflictError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanupOperationConflictError overwrites any union data inside the CleanupAgentSessionV2409JSONResponseBody as the provided CleanupOperationConflictError
func (t *CleanupAgentSessionV2409JSONResponseBody) FromCleanupOperationConflictError(v CleanupOperationConflictError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanupOperationConflictError performs a merge with any union data inside the CleanupAgentSessionV2409JSONResponseBody, using the provided CleanupOperationConflictError
func (t *CleanupAgentSessionV2409JSONResponseBody) MergeCleanupOperationConflictError(v CleanupOperationConflictError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CleanupAgentSessionV2409JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CleanupAgentSessionV2409JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsErrorResponse returns the union data inside the StartAgentTurnV2409JSONResponseBody as a ErrorResponse
func (t StartAgentTurnV2409JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the StartAgentTurnV2409JSONResponseBody as the provided ErrorResponse
func (t *StartAgentTurnV2409JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the StartAgentTurnV2409JSONResponseBody, using the provided ErrorResponse
func (t *StartAgentTurnV2409JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTurnOperationConflictError returns the union data inside the StartAgentTurnV2409JSONResponseBody as a TurnOperationConflictError
func (t StartAgentTurnV2409JSONResponseBody) AsTurnOperationConflictError() (TurnOperationConflictError, error) {
	var body TurnOperationConflictError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTurnOperationConflictError overwrites any union data inside the StartAgentTurnV2409JSONResponseBody as the provided TurnOperationConflictError
func (t *StartAgentTurnV2409JSONResponseBody) FromTurnOperationConflictError(v TurnOperationConflictError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTurnOperationConflictError performs a merge with any union data inside the StartAgentTurnV2409JSONResponseBody, using the provided TurnOperationConflictError
func (t *StartAgentTurnV2409JSONResponseBody) MergeTurnOperationConflictError(v TurnOperationConflictError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StartAgentTurnV2409JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StartAgentTurnV2409JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
